import pickle

ticker_list = {
    "10x Genomics Inc. (TXG)":["TXG","10x"],
    "1Life Healthcare Inc. (ONEM)":["ONEM","1Life"],
    "2U Inc. (TWOU)":["TWOU","2U"],
    "3D Systems Corporation (DDD)":["DDD","3D"],
    "3M Company (MMM)":["MMM","3M"],
    "8x8 Inc (EGHT)":["EGHT","8x8"],
    "A.O. Smith Corporation (AOS)":["AOS","A.O."],
    "AAON Inc. (AAON)":["AAON","AAON"],
    "Abbott Laboratories (ABT)":["ABT","Abbott"],
    "AbbVie Inc. (ABBV)":["ABBV","AbbVie"],
    "AbCellera Biologics Inc. (ABCL)":["ABCL","AbCellera"],
    "Abercrombie & Fitch Company (ANF)":["ANF","Abercrombie"],
    "ABIOMED Inc. (ABMD)":["ABMD","ABIOMED"],
    "ABM Industries Incorporated (ABM)":["ABM","ABM"],
    "Academy Sports and Outdoors Inc. (ASO)":["ASO","Academy"],
    "Acadia Healthcare Company Inc. (ACHC)":["ACHC","Acadia"],
    "ACADIA Pharmaceuticals Inc. (ACAD)":["ACAD","ACADIA"],
    "Acceleron Pharma Inc. (XLRN)":["XLRN","Acceleron"],
    "Accolade Inc. (ACCD)":["ACCD","Accolade"],
    "ACI Worldwide Inc. (ACIW)":["ACIW","ACI"],
    "Activision Blizzard Inc. (ATVI)":["ATVI","Activision"],
    "Acuity Brands Inc. (AYI)":["AYI","Acuity"],
    "Acushnet Holdings Corp. (GOLF)":["GOLF","Acushnet"],
    "ACV Auctions Inc. (ACVA)":["ACVA","ACV"],
    "Adams Diversified Equity Fund Inc. (ADX)":["ADX","Adams"],
    "AdaptHealth Corp. (AHCO)":["AHCO","AdaptHealth"],
    "Adaptive Biotechnologies Corporation (ADPT)":["ADPT","Adaptive"],
    "Adobe Inc. (ADBE)":["ADBE","Adobe"],
    "ADT Inc. (ADT)":["ADT","ADT"],
    "Adtalem Global Education Inc. (ATGE)":["ATGE","Adtalem"],
    "Advance Auto Parts Inc Advance Auto Parts Inc W/I (AAP)":["AAP","Advance"],
    "Advanced Drainage Systems Inc. (WMS)":["WMS","Advanced"],
    "Advanced Energy Industries Inc. (AEIS)":["AEIS","Advanced"],
    "Advanced Micro Devices Inc. (AMD)":["AMD","Advanced"],
    "Advantage Solutions Inc. (ADV)":["ADV","Advantage"],
    "AECOM (ACM)":["ACM","AECOM"],
    "Aerojet Rocketdyne Holdings Inc. (AJRD)":["AJRD","Aerojet"],
    "AeroVironment Inc. (AVAV)":["AVAV","AeroVironment"],
    "Affiliated Managers Group Inc. (AMG)":["AMG","Affiliated"],
    "Affirm Holdings Inc. (AFRM)":["AFRM","Affirm"],
    "AFLAC Incorporated (AFL)":["AFL","AFLAC"],
    "AGCO Corporation (AGCO)":["AGCO","AGCO"],
    "Agilent Technologies Inc. (A)":["A","Agilent"],
    "Agios Pharmaceuticals Inc. (AGIO)":["AGIO","Agios"],
    "AGNC Investment Corp. (AGNC)":["AGNC","AGNC"],
    "Agnico Eagle Mines Limited (AEM)":["AEM","Agnico"],
    "Agree Realty Corporation (ADC)":["ADC","Agree"],
    "Air Lease Corporation (AL)":["AL","Air"],
    "Air Products and Chemicals Inc. (APD)":["APD","Air"],
    "Airbnb Inc. (ABNB)":["ABNB","Airbnb"],
    "Akamai Technologies Inc. (AKAM)":["AKAM","Akamai"],
    "Alamos Gold Inc. (AGI)":["AGI","Alamos"],
    "Alarm.com Holdings Inc. (ALRM)":["ALRM","Alarm.com"],
    "Alaska Air Group Inc. (ALK)":["ALK","Alaska"],
    "Albany International Corporation (AIN)":["AIN","Albany"],
    "Albemarle Corporation (ALB)":["ALB","Albemarle"],
    "Albertsons Companies Inc. (ACI)":["ACI","Albertsons"],
    "Alexandria Real Estate Equities Inc. (ARE)":["ARE","Alexandria"],
    "Alexion Pharmaceuticals Inc. (ALXN)":["ALXN","Alexion"],
    "Align Technology Inc. (ALGN)":["ALGN","Align"],
    "Alignment Healthcare Inc. (ALHC)":["ALHC","Alignment"],
    "Allakos Inc. (ALLK)":["ALLK","Allakos"],
    "Alleghany Corporation (Y)":["Y","Alleghany"],
    "Allegheny Technologies Incorporated (ATI)":["ATI","Allegheny"],
    "Allegiant Travel Company (ALGT)":["ALGT","Allegiant"],
    "Allegion plc (ALLE)":["ALLE","Allegion"],
    "Allegro MicroSystems Inc. (ALGM)":["ALGM","Allegro"],
    "Allete Inc. (ALE)":["ALE","Allete"],
    "Alliance Data Systems Corporation (ADS)":["ADS","Alliance"],
    "AllianceBernstein Holding L.P. Units (AB)":["AB","AllianceBernstein"],
    "Alliant Energy Corporation (LNT)":["LNT","Alliant"],
    "Allison Transmission Holdings Inc. (ALSN)":["ALSN","Allison"],
    "Allogene Therapeutics Inc. (ALLO)":["ALLO","Allogene"],
    "Allscripts Healthcare Solutions Inc. (MDRX)":["MDRX","Allscripts"],
    "Allstate Corporation (ALL)":["ALL","Allstate"],
    "Ally Financial Inc. (ALLY)":["ALLY","Ally"],
    "Alnylam Pharmaceuticals Inc. (ALNY)":["ALNY","Alnylam"],
    "Alphabet Inc. (GOOGL)":["GOOGL","Alphabet"],
    "Alphabet Inc. Capital Stock (GOOG)":["GOOG","Alphabet"],
    "Altair Engineering Inc. (ALTR)":["ALTR","Altair"],
    "Alteryx Inc. (AYX)":["AYX","Alteryx"],
    "Altice USA Inc. (ATUS)":["ATUS","Altice"],
    "Altra Industrial Motion Corp. (AIMC)":["AIMC","Altra"],
    "Altria Group Inc. (MO)":["MO","Altria"],
    "ALX Oncology Holdings Inc. (ALXO)":["ALXO","ALX"],
    "Amazon.com Inc. (AMZN)":["AMZN","Amazon"],
    "Ambarella Inc. (AMBA)":["AMBA","Ambarella"],
    "AMC Networks Inc. (AMC)":["AMC","AMC"],
    "Amedisys Inc (AMED)":["AMED","Amedisys"],
    "Amerco (UHAL)":["UHAL","Amerco"],
    "Ameren Corporation (AEE)":["AEE","Ameren"],
    "Ameresco Inc. (AMRC)":["AMRC","Ameresco"],
    "America Movil S.A.B. de C.V. American Depositary Shares (AMOV)":["AMOV","America"],
    "America Movil S.A.B. de C.V. American Depository Receipt Series L (AMX)":["AMX","America"],
    "American Airlines Group Inc. (AAL)":["AAL","American"],
    "American Assets Trust Inc. (AAT)":["AAT","American"],
    "American Campus Communities Inc (ACC)":["ACC","American"],
    "American Eagle Outfitters Inc. (AEO)":["AEO","American"],
    "American Electric Power Company Inc. (AEP)":["AEP","American"],
    "American Equity Investment Life Holding Company (AEL)":["AEL","American"],
    "American Express Company (AXP)":["AXP","American"],
    "American Financial Group Inc. (AFG)":["AFG","American"],
    "American International Group Inc. New (AIG)":["AIG","American"],
    "American National Group Inc. (ANAT)":["ANAT","American"],
    "American States Water Company (AWR)":["AWR","American"],
    "American Tower Corporation (AMT)":["AMT","American"],
    "American Water Works Company Inc. (AWK)":["AWK","American"],
    "American Well Corporation (AMWL)":["AMWL","American"],
    "Americold Realty Trust (COLD)":["COLD","Americold"],
    "Ameriprise Financial Inc. (AMP)":["AMP","Ameriprise"],
    "Ameris Bancorp (ABCB)":["ABCB","Ameris"],
    "AmerisourceBergen Corporation (ABC)":["ABC","AmerisourceBergen"],
    "AMETEK Inc. (AME)":["AME","AMETEK"],
    "Amgen Inc. (AMGN)":["AMGN","Amgen"],
    "Amicus Therapeutics Inc. (FOLD)":["FOLD","Amicus"],
    "Amkor Technology Inc. (AMKR)":["AMKR","Amkor"],
    "AMN Healthcare Services Inc AMN Healthcare Services Inc (AMN)":["AMN","AMN"],
    "Amphenol Corporation (APH)":["APH","Amphenol"],
    "Amyris Inc. (AMRS)":["AMRS","Amyris"],
    "Analog Devices Inc. (ADI)":["ADI","Analog"],
    "Anaplan Inc. (PLAN)":["PLAN","Anaplan"],
    "Angi Inc. (ANGI)":["ANGI","Angi"],
    "Annaly Capital Management Inc (NLY)":["NLY","Annaly"],
    "ANSYS Inc. (ANSS)":["ANSS","ANSYS"],
    "Antero Midstream Corporation (AM)":["AM","Antero"],
    "Anthem Inc. (ANTM)":["ANTM","Anthem"],
    "Aon plc (AON)":["AON","Aon"],
    "APA Corporation (APA)":["APA","APA"],
    "Apellis Pharmaceuticals Inc. (APLS)":["APLS","Apellis"],
    "Aphria Inc. (APHA)":["APHA","Aphria"],
    "Apollo Global Management Inc. (APO)":["APO","Apollo"],
    "AppFolio Inc. (APPF)":["APPF","AppFolio"],
    "Appian Corporation (APPN)":["APPN","Appian"],
    "Apple Hospitality REIT Inc. (APLE)":["APLE","Apple"],
    "Apple Inc. (AAPL)":["AAPL","Apple"],
    "Applied Industrial Technologies Inc. (AIT)":["AIT","Applied"],
    "Applied Materials Inc. (AMAT)":["AMAT","Applied"],
    "AptarGroup Inc. (ATR)":["ATR","AptarGroup"],
    "Arbor Realty Trust (ABR)":["ABR","Arbor"],
    "Archer-Daniels-Midland Company (ADM)":["ADM","Archer-Daniels-Midland"],
    "Arena Pharmaceuticals Inc. (ARNA)":["ARNA","Arena"],
    "Ares Capital Corporation (ARCC)":["ARCC","Ares"],
    "Armstrong World Industries Inc (AWI)":["AWI","Armstrong"],
    "Array Technologies Inc. (ARRY)":["ARRY","Array"],
    "Arrow Electronics Inc. (ARW)":["ARW","Arrow"],
    "Arrowhead Pharmaceuticals Inc. (ARWR)":["ARWR","Arrowhead"],
    "Arthur J. Gallagher & Co. (AJG)":["AJG","Arthur"],
    "Artisan Partners Asset Management Inc. (APAM)":["APAM","Artisan"],
    "Arvinas Inc. (ARVN)":["ARVN","Arvinas"],
    "Asbury Automotive Group Inc (ABG)":["ABG","Asbury"],
    "ASGN Incorporated (ASGN)":["ASGN","ASGN"],
    "Ashland Global Holdings Inc. (ASH)":["ASH","Ashland"],
    "Aspen Technology Inc. (AZPN)":["AZPN","Aspen"],
    "Associated Banc-Corp (ASB)":["ASB","Associated"],
    "Assurant Inc. (AIZ)":["AIZ","Assurant"],
    "AT&T Inc. (T)":["T","AT&T"],
    "Atea Pharmaceuticals Inc. (AVIR)":["AVIR","Atea"],
    "Atkore Inc. (ATKR)":["ATKR","Atkore"],
    "Atlantic Union Bankshares Corporation (AUB)":["AUB","Atlantic"],
    "Atmos Energy Corporation (ATO)":["ATO","Atmos"],
    "AtriCure Inc. (ATRC)":["ATRC","AtriCure"],
    "Autodesk Inc. (ADSK)":["ADSK","Autodesk"],
    "Automatic Data Processing Inc. (ADP)":["ADP","Automatic"],
    "AutoNation Inc. (AN)":["AN","AutoNation"],
    "AutoZone Inc. (AZO)":["AZO","AutoZone"],
    "Avalara Inc. (AVLR)":["AVLR","Avalara"],
    "AvalonBay Communities Inc. (AVB)":["AVB","AvalonBay"],
    "Avangrid Inc. (AGR)":["AGR","Avangrid"],
    "Avanos Medical Inc. (AVNS)":["AVNS","Avanos"],
    "Avery Dennison Corporation (AVY)":["AVY","Avery"],
    "Avient Corporation (AVNT)":["AVNT","Avient"],
    "Avis Budget Group Inc. (CAR)":["CAR","Avis"],
    "Avista Corporation (AVA)":["AVA","Avista"],
    "Avnet Inc. (AVT)":["AVT","Avnet"],
    "Axalta Coating Systems Ltd. (AXTA)":["AXTA","Axalta"],
    "Axon Enterprise Inc. (AXON)":["AXON","Axon"],
    "Axonics Modulation Technologies Inc. (AXNX)":["AXNX","Axonics"],
    "Axos Financial Inc. (AX)":["AX","Axos"],
    "Axsome Therapeutics Inc. (AXSM)":["AXSM","Axsome"],
    "Badger Meter Inc. (BMI)":["BMI","Badger"],
    "Balchem Corporation (BCPC)":["BCPC","Balchem"],
    "Ball Corporation (BLL)":["BLL","Ball"],
    "Ballard Power Systems Inc. (BLDP)":["BLDP","Ballard"],
    "BancFirst Corporation (BANF)":["BANF","BancFirst"],
    "Banco Santander Mexico S.A. Institucion de Banca Multiple Grupo Financiero Santander Mexico (BSMX)":["BSMX","Banco"],
    "BancorpSouth Bank (BXS)":["BXS","BancorpSouth"],
    "Bandwidth Inc. (BAND)":["BAND","Bandwidth"],
    "Bank Nova Scotia Halifax Pfd 3 (BNS)":["BNS","Bank"],
    "Bank of America Corporation (BAC)":["BAC","Bank"],
    "Bank of Hawaii Corporation (BOH)":["BOH","Bank"],
    "Bank Of Montreal (BMO)":["BMO","Bank"],
    "Bank OZK (OZK)":["OZK","Bank"],
    "BankUnited Inc. (BKU)":["BKU","BankUnited"],
    "Barnes Group Inc. (B)":["B","Barnes"],
    "Barrick Gold Corporation (GOLD)":["GOLD","Barrick"],
    "Bausch Health Companies Inc. (BHC)":["BHC","Bausch"],
    "Baxter International Inc. (BAX)":["BAX","Baxter"],
    "BCE Inc. (BCE)":["BCE","BCE"],
    "Beacon Roofing Supply Inc. (BECN)":["BECN","Beacon"],
    "Beam Therapeutics Inc. (BEAM)":["BEAM","Beam"],
    "Becton Dickinson and Company (BDX)":["BDX","Becton"],
    "Bed Bath & Beyond Inc. (BBBY)":["BBBY","Bed"],
    "Belden Inc (BDC)":["BDC","Belden"],
    "Bentley Systems Incorporated (BSY)":["BSY","Bentley"],
    "Berkeley Lights Inc. (BLI)":["BLI","Berkeley"],
    "Berry Global Group Inc. (BERY)":["BERY","Berry"],
    "Best Buy Co. Inc. (BBY)":["BBY","Best"],
    "Beyond Meat Inc. (BYND)":["BYND","Beyond"],
    "BGC Partners Inc (BGCP)":["BGCP","BGC"],
    "Big Lots Inc. (BIG)":["BIG","Big"],
    "BigCommerce Holdings Inc. (BIGC)":["BIGC","BigCommerce"],
    "Bio-Rad Laboratories Inc. (BIO)":["BIO","Bio-Rad"],
    "Bio-Techne Corp (TECH)":["TECH","Bio-Techne"],
    "Biogen Inc. (BIIB)":["BIIB","Biogen"],
    "Biohaven Pharmaceutical Holding Company Ltd. (BHVN)":["BHVN","Biohaven"],
    "BioMarin Pharmaceutical Inc. (BMRN)":["BMRN","BioMarin"],
    "Bionano Genomics Inc. (BNGO)":["BNGO","Bionano"],
    "BJ's Wholesale Club Holdings Inc. (BJ)":["BJ","BJ's"],
    "Black Hills Corporation (BKH)":["BKH","Black"],
    "Blackbaud Inc. (BLKB)":["BLKB","Blackbaud"],
    "BlackBerry Limited (BB)":["BB","BlackBerry"],
    "BlackLine Inc. (BL)":["BL","BlackLine"],
    "BlackRock Capital Allocation Trust of Beneficial Interest (BCAT)":["BCAT","BlackRock"],
    "BlackRock Inc. (BLK)":["BLK","BlackRock"],
    "Blackstone Mortgage Trust Inc. (BXMT)":["BXMT","Blackstone"],
    "Bloomin' Brands Inc. (BLMN)":["BLMN","Bloomin'"],
    "bluebird bio Inc. (BLUE)":["BLUE","bluebird"],
    "Blueprint Medicines Corporation (BPMC)":["BPMC","Blueprint"],
    "Boeing Company (BA)":["BA","Boeing"],
    "Boise Cascade L.L.C. (BCC)":["BCC","Boise"],
    "BOK Financial Corporation (BOKF)":["BOKF","BOK"],
    "Booking Holdings Inc. (BKNG)":["BKNG","Booking"],
    "Booz Allen Hamilton Holding Corporation (BAH)":["BAH","Booz"],
    "BorgWarner Inc. (BWA)":["BWA","BorgWarner"],
    "Boston Beer Company Inc. (SAM)":["SAM","Boston"],
    "Boston Properties Inc. (BXP)":["BXP","Boston"],
    "Boston Scientific Corporation (BSX)":["BSX","Boston"],
    "Bottomline Technologies Inc. (EPAY)":["EPAY","Bottomline"],
    "Box Inc. (BOX)":["BOX","Box"],
    "Boyd Gaming Corporation (BYD)":["BYD","Boyd"],
    "Brady Corporation (BRC)":["BRC","Brady"],
    "Brandywine Realty Trust (BDN)":["BDN","Brandywine"],
    "BridgeBio Pharma Inc. (BBIO)":["BBIO","BridgeBio"],
    "Bright Horizons Family Solutions Inc. (BFAM)":["BFAM","Bright"],
    "Brighthouse Financial Inc. (BHF)":["BHF","Brighthouse"],
    "Brinker International Inc. (EAT)":["EAT","Brinker"],
    "Brinks Company (BCO)":["BCO","Brinks"],
    "Bristol-Myers Squibb Company (BMY)":["BMY","Bristol-Myers"],
    "Broadcom Inc. (AVGO)":["AVGO","Broadcom"],
    "Broadridge Financial Solutions Inc. (BR)":["BR","Broadridge"],
    "Broadstone Net Lease Inc. (BNL)":["BNL","Broadstone"],
    "Brookfield Asset Management Inc. (BAM)":["BAM","Brookfield"],
    "Brooks Automation Inc. (BRKS)":["BRKS","Brooks"],
    "Brown & Brown Inc. (BRO)":["BRO","Brown"],
    "Bruker Corporation (BRKR)":["BRKR","Bruker"],
    "Brunswick Corporation (BC)":["BC","Brunswick"],
    "BTRS Holdings Inc. Class 1 (BTRS)":["BTRS","BTRS"],
    "Builders FirstSource Inc. (BLDR)":["BLDR","Builders"],
    "Bumble Inc. (BMBL)":["BMBL","Bumble"],
    "Bunge Limited Bunge Limited (BG)":["BG","Bunge"],
    "BWX Technologies Inc. (BWXT)":["BWXT","BWX"],
    "C.H. Robinson Worldwide Inc. (CHRW)":["CHRW","C.H."],
    "Cable One Inc. (CABO)":["CABO","Cable"],
    "Cabot Corporation (CBT)":["CBT","Cabot"],
    "Cabot Oil & Gas Corporation (COG)":["COG","Cabot"],
    "CACI International Inc. (CACI)":["CACI","CACI"],
    "Cadence Bancorporation (CADE)":["CADE","Cadence"],
    "Cadence Design Systems Inc. (CDNS)":["CDNS","Cadence"],
    "CAE Inc. (CAE)":["CAE","CAE"],
    "Caesars Entertainment Inc. (CZR)":["CZR","Caesars"],
    "Calamos Strategic Total Return (CSQ)":["CSQ","Calamos"],
    "California Water Service Group (CWT)":["CWT","California"],
    "Calix Inc (CALX)":["CALX","Calix"],
    "Callaway Golf Company (ELY)":["ELY","Callaway"],
    "Camden Property Trust (CPT)":["CPT","Camden"],
    "Cameco Corporation (CCJ)":["CCJ","Cameco"],
    "Campbell Soup Company (CPB)":["CPB","Campbell"],
    "Camping World Holdings Inc. (CWH)":["CWH","Camping"],
    "Canadian Imperial Bank of Commerce (CM)":["CM","Canadian"],
    "Canadian National Railway Company (CNI)":["CNI","Canadian"],
    "Canadian Natural Resources Limited (CNQ)":["CNQ","Canadian"],
    "Canadian Pacific Railway Limited (CP)":["CP","Canadian"],
    "Canoo Inc. (GOEV)":["GOEV","Canoo"],
    "Canopy Growth Corporation (CGC)":["CGC","Canopy"],
    "Cantel Medical Corp. (CMD)":["CMD","Cantel"],
    "Capital One Financial Corporation (COF)":["COF","Capital"],
    "Cardinal Health Inc. (CAH)":["CAH","Cardinal"],
    "Cardlytics Inc. (CDLX)":["CDLX","Cardlytics"],
    "CareDx Inc. (CDNA)":["CDNA","CareDx"],
    "CareTrust REIT Inc. (CTRE)":["CTRE","CareTrust"],
    "CarGurus Inc. (CARG)":["CARG","CarGurus"],
    "Carlisle Companies Incorporated (CSL)":["CSL","Carlisle"],
    "CarMax Inc (KMX)":["KMX","CarMax"],
    "Carnival Corporation (CCL)":["CCL","Carnival"],
    "Carnival Plc ADS ADS (CUK)":["CUK","Carnival"],
    "Carpenter Technology Corporation (CRS)":["CRS","Carpenter"],
    "Carter's Inc. (CRI)":["CRI","Carter's"],
    "Carvana Co. (CVNA)":["CVNA","Carvana"],
    "Casella Waste Systems Inc. (CWST)":["CWST","Casella"],
    "Casey's General Stores Inc. (CASY)":["CASY","Casey's"],
    "Catalent Inc. (CTLT)":["CTLT","Catalent"],
    "Caterpillar Inc. (CAT)":["CAT","Caterpillar"],
    "Cathay General Bancorp (CATY)":["CATY","Cathay"],
    "Cavco Industries Inc. When Issued (CVCO)":["CVCO","Cavco"],
    "CBRE Group Inc (CBRE)":["CBRE","CBRE"],
    "CDK Global Inc. (CDK)":["CDK","CDK"],
    "CDW Corporation (CDW)":["CDW","CDW"],
    "Cedar Fair L.P. (FUN)":["FUN","Cedar"],
    "Celanese Corporation Celanese Corporation (CE)":["CE","Celanese"],
    "Celsius Holdings Inc. (CELH)":["CELH","Celsius"],
    "Cemex S.A.B. de C.V. Sponsored ADR (CX)":["CX","Cemex"],
    "Cenovus Energy Inc (CVE)":["CVE","Cenovus"],
    "Centene Corporation (CNC)":["CNC","Centene"],
    "CenterPoint Energy Inc (CNP)":["CNP","CenterPoint"],
    "Central Garden & Pet Company (CENT)":["CENT","Central"],
    "Central Garden & Pet Company Nonvoting (CENTA)":["CENTA","Central"],
    "Century Communities Inc. (CCS)":["CCS","Century"],
    "Cerence Inc. (CRNC)":["CRNC","Cerence"],
    "Ceridian HCM Holding Inc. (CDAY)":["CDAY","Ceridian"],
    "Cerner Corporation (CERN)":["CERN","Cerner"],
    "Certara Inc. (CERT)":["CERT","Certara"],
    "CF Industries Holdings Inc. (CF)":["CF","CF"],
    "CGI Inc. (GIB)":["GIB","CGI"],
    "ChampionX Corporation (CHX)":["CHX","ChampionX"],
    "Change Healthcare Inc. (CHNG)":["CHNG","Change"],
    "Charles River Laboratories International Inc. (CRL)":["CRL","Charles"],
    "Charles Schwab Corporation (SCHW)":["SCHW","Charles"],
    "Chart Industries Inc. (GTLS)":["GTLS","Chart"],
    "Charter Communications Inc. New (CHTR)":["CHTR","Charter"],
    "Cheesecake Factory Incorporated (CAKE)":["CAKE","Cheesecake"],
    "Chemed Corp (CHE)":["CHE","Chemed"],
    "ChemoCentryx Inc. (CCXI)":["CCXI","ChemoCentryx"],
    "Chemours Company (CC)":["CC","Chemours"],
    "Chesapeake Energy Corporation (CHK)":["CHK","Chesapeake"],
    "Chesapeake Utilities Corporation (CPK)":["CPK","Chesapeake"],
    "Chevron Corporation (CVX)":["CVX","Chevron"],
    "Chimera Investment Corporation (CIM)":["CIM","Chimera"],
    "Chipotle Mexican Grill Inc. (CMG)":["CMG","Chipotle"],
    "Choice Hotels International Inc. (CHH)":["CHH","Choice"],
    "Church & Dwight Company Inc. (CHD)":["CHD","Church"],
    "Churchill Capital Corp IV (CCIV)":["CCIV","Churchill"],
    "Churchill Downs Incorporated (CHDN)":["CHDN","Churchill"],
    "Ciena Corporation (CIEN)":["CIEN","Ciena"],
    "Cigna Corporation (CI)":["CI","Cigna"],
    "Cimarex Energy Co (XEC)":["XEC","Cimarex"],
    "Cincinnati Financial Corporation (CINF)":["CINF","Cincinnati"],
    "Cinemark Holdings Inc Cinemark Holdings Inc. (CNK)":["CNK","Cinemark"],
    "Cintas Corporation (CTAS)":["CTAS","Cintas"],
    "Cirrus Logic Inc. (CRUS)":["CRUS","Cirrus"],
    "Cisco Systems Inc. (CSCO)":["CSCO","Cisco"],
    "CIT Group Inc (CIT)":["CIT","CIT"],
    "Citigroup Inc. (C)":["C","Citigroup"],
    "Citizens Financial Group Inc. (CFG)":["CFG","Citizens"],
    "Citrix Systems Inc. (CTXS)":["CTXS","Citrix"],
    "Clean Energy Fuels Corp. (CLNE)":["CLNE","Clean"],
    "Clean Harbors Inc. (CLH)":["CLH","Clean"],
    "Clearway Energy Inc. (CWEN)":["CWEN","Clearway"],
    "Cleveland-Cliffs Inc. (CLF)":["CLF","Cleveland-Cliffs"],
    "Clorox Company (CLX)":["CLX","Clorox"],
    "Cloudera Inc. (CLDR)":["CLDR","Cloudera"],
    "Cloudflare Inc. (NET)":["NET","Cloudflare"],
    "Clover Health Investments Corp. (CLOV)":["CLOV","Clover"],
    "CMC Materials Inc. (CCMP)":["CCMP","CMC"],
    "CME Group Inc. (CME)":["CME","CME"],
    "CMS Energy Corporation (CMS)":["CMS","CMS"],
    "CNA Financial Corporation (CNA)":["CNA","CNA"],
    "CNO Financial Group Inc. (CNO)":["CNO","CNO"],
    "CNX Resources Corporation (CNX)":["CNX","CNX"],
    "Coca Cola Femsa S.A.B. de C.V. (KOF)":["KOF","Coca"],
    "Coca-Cola Company (KO)":["KO","Coca-Cola"],
    "Coca-Cola Consolidated Inc. (COKE)":["COKE","Coca-Cola"],
    "Coeur Mining Inc. (CDE)":["CDE","Coeur"],
    "Cogent Communications Holdings Inc. (CCOI)":["CCOI","Cogent"],
    "Cognex Corporation (CGNX)":["CGNX","Cognex"],
    "Cognizant Technology Solutions Corporation (CTSH)":["CTSH","Cognizant"],
    "Cohen & Steers Inc (CNS)":["CNS","Cohen"],
    "Cohen & Steers Infrastructure Fund Inc (UTF)":["UTF","Cohen"],
    "Coherent Inc. (COHR)":["COHR","Coherent"],
    "Cohu Inc. (COHU)":["COHU","Cohu"],
    "Colfax Corporation (CFX)":["CFX","Colfax"],
    "Colgate-Palmolive Company (CL)":["CL","Colgate-Palmolive"],
    "Colliers International Group Inc. Subordinate Voting Shares (CIGI)":["CIGI","Colliers"],
    "Colony Capital Inc. (CLNY)":["CLNY","Colony"],
    "Columbia Banking System Inc. (COLB)":["COLB","Columbia"],
    "Columbia Sportswear Company (COLM)":["COLM","Columbia"],
    "Comcast Corporation (CMCSA)":["CMCSA","Comcast"],
    "Comerica Incorporated (CMA)":["CMA","Comerica"],
    "Comfort Systems USA Inc. (FIX)":["FIX","Comfort"],
    "Commerce Bancshares Inc. (CBSH)":["CBSH","Commerce"],
    "Commercial Metals Company (CMC)":["CMC","Commercial"],
    "CommScope Holding Company Inc. (COMM)":["COMM","CommScope"],
    "Community Bank System Inc. (CBU)":["CBU","Community"],
    "Commvault Systems Inc. (CVLT)":["CVLT","Commvault"],
    "Compass Minerals Intl Inc (CMP)":["CMP","Compass"],
    "ConAgra Brands Inc. (CAG)":["CAG","ConAgra"],
    "Concentrix Corporation (CNXC)":["CNXC","Concentrix"],
    "CONMED Corporation (CNMD)":["CNMD","CONMED"],
    "ConocoPhillips (COP)":["COP","ConocoPhillips"],
    "Consolidated Edison Inc. (ED)":["ED","Consolidated"],
    "Constellation Brands Inc. (STZ)":["STZ","Constellation"],
    "ContextLogic Inc. (WISH)":["WISH","ContextLogic"],
    "Continental Resources Inc. (CLR)":["CLR","Continental"],
    "Cooper Tire & Rubber Company (CTB)":["CTB","Cooper"],
    "Copart Inc. (CPRT)":["CPRT","Copart"],
    "Corcept Therapeutics Incorporated (CORT)":["CORT","Corcept"],
    "CoreLogic Inc. (CLGX)":["CLGX","CoreLogic"],
    "CoreSite Realty Corporation (COR)":["COR","CoreSite"],
    "Cornerstone OnDemand Inc. (CSOD)":["CSOD","Cornerstone"],
    "Corning Incorporated (GLW)":["GLW","Corning"],
    "Corporate Office Properties Trust (OFC)":["OFC","Corporate"],
    "Corsair Gaming Inc. (CRSR)":["CRSR","Corsair"],
    "CoStar Group Inc. (CSGP)":["CSGP","CoStar"],
    "Costco Wholesale Corporation (COST)":["COST","Costco"],
    "Coty Inc. (COTY)":["COTY","Coty"],
    "Coupa Software Incorporated (COUP)":["COUP","Coupa"],
    "Cousins Properties Incorporated (CUZ)":["CUZ","Cousins"],
    "Covetrus Inc. (CVET)":["CVET","Covetrus"],
    "Cracker Barrel Old Country Store Inc (CBRL)":["CBRL","Cracker"],
    "Crane Co. (CR)":["CR","Crane"],
    "Credit Acceptance Corporation (CACC)":["CACC","Credit"],
    "Cree Inc. (CREE)":["CREE","Cree"],
    "Crescent Point Energy Corporation (CPG)":["CPG","Crescent"],
    "Cricut Inc. (CRCT)":["CRCT","Cricut"],
    "Crocs Inc. (CROX)":["CROX","Crocs"],
    "Cronos Group Inc. (CRON)":["CRON","Cronos"],
    "CrowdStrike Holdings Inc. (CRWD)":["CRWD","CrowdStrike"],
    "Crown Castle International Corp. (CCI)":["CCI","Crown"],
    "Crown Holdings Inc. (CCK)":["CCK","Crown"],
    "CryoPort Inc. (CYRX)":["CYRX","CryoPort"],
    "CSW Industrials Inc. (CSWI)":["CSWI","CSW"],
    "CSX Corporation (CSX)":["CSX","CSX"],
    "CubeSmart (CUBE)":["CUBE","CubeSmart"],
    "Cubic Corporation (CUB)":["CUB","Cubic"],
    "Cullen/Frost Bankers Inc. (CFR)":["CFR","Cullen/Frost"],
    "Cummins Inc. (CMI)":["CMI","Cummins"],
    "Curtiss-Wright Corporation (CW)":["CW","Curtiss-Wright"],
    "CVB Financial Corporation (CVBF)":["CVBF","CVB"],
    "CVS Health Corporation (CVS)":["CVS","CVS"],
    "CyrusOne Inc (CONE)":["CONE","CyrusOne"],
    "D.R. Horton Inc. (DHI)":["DHI","D.R."],
    "D/B/A Royal Caribbean Cruises Ltd. (RCL)":["RCL","D/B/A"],
    "Dana Incorporated (DAN)":["DAN","Dana"],
    "Danaher Corporation (DHR)":["DHR","Danaher"],
    "Darden Restaurants Inc. (DRI)":["DRI","Darden"],
    "Darling Ingredients Inc. (DAR)":["DAR","Darling"],
    "Datadog Inc. (DDOG)":["DDOG","Datadog"],
    "Datto Holding Corp. (MSP)":["MSP","Datto"],
    "Dave & Buster's Entertainment Inc. (PLAY)":["PLAY","Dave"],
    "DaVita Inc. (DVA)":["DVA","DaVita"],
    "DCP Midstream LP (DCP)":["DCP","DCP"],
    "Deciphera Pharmaceuticals Inc. (DCPH)":["DCPH","Deciphera"],
    "Deckers Outdoor Corporation (DECK)":["DECK","Deckers"],
    "Deere & Company (DE)":["DE","Deere"],
    "Delta Air Lines Inc. (DAL)":["DAL","Delta"],
    "Denali Therapeutics Inc. (DNLI)":["DNLI","Denali"],
    "DENTSPLY SIRONA Inc. (XRAY)":["XRAY","DENTSPLY"],
    "Descartes Systems Group Inc. (DSGX)":["DSGX","Descartes"],
    "Devon Energy Corporation (DVN)":["DVN","Devon"],
    "DexCom Inc. (DXCM)":["DXCM","DexCom"],
    "Diamondback Energy Inc. Commmon Stock (FANG)":["FANG","Diamondback"],
    "Diamondrock Hospitality Company (DRH)":["DRH","Diamondrock"],
    "Dick's Sporting Goods Inc (DKS)":["DKS","Dick's"],
    "Digital Realty Trust Inc. (DLR)":["DLR","Digital"],
    "Digital Turbine Inc. (APPS)":["APPS","Digital"],
    "Dillard's Inc. (DDS)":["DDS","Dillard's"],
    "Diodes Incorporated (DIOD)":["DIOD","Diodes"],
    "Discover Financial Services (DFS)":["DFS","Discover"],
    "Discovery Inc. Series A (DISCA)":["DISCA","Discovery"],
    "Discovery Inc. Series B (DISCB)":["DISCB","Discovery"],
    "Discovery Inc. Series C (DISCK)":["DISCK","Discovery"],
    "DISH Network Corporation (DISH)":["DISH","DISH"],
    "Diversey Holdings Ltd. (DSEY)":["DSEY","Diversey"],
    "DNP Select Income Fund Inc. (DNP)":["DNP","DNP"],
    "DocuSign Inc. (DOCU)":["DOCU","DocuSign"],
    "Dolby Laboratories (DLB)":["DLB","Dolby"],
    "Dollar General Corporation (DG)":["DG","Dollar"],
    "Dollar Tree Inc. (DLTR)":["DLTR","Dollar"],
    "Dominion Energy Inc. (D)":["D","Dominion"],
    "Domino's Pizza Inc (DPZ)":["DPZ","Domino's"],
    "Donaldson Company Inc. (DCI)":["DCI","Donaldson"],
    "Dorman Products Inc. (DORM)":["DORM","Dorman"],
    "Douglas Emmett Inc. (DEI)":["DEI","Douglas"],
    "Dover Corporation (DOV)":["DOV","Dover"],
    "DraftKings Inc. (DKNG)":["DKNG","DraftKings"],
    "Dream Finders Homes Inc. (DFH)":["DFH","Dream"],
    "Driven Brands Holdings Inc. (DRVN)":["DRVN","Driven"],
    "Dropbox Inc. (DBX)":["DBX","Dropbox"],
    "DTE Energy Company (DTE)":["DTE","DTE"],
    "Duck Creek Technologies Inc. (DCT)":["DCT","Duck"],
    "Duke Energy Corporation (DUK)":["DUK","Duke"],
    "Duke Realty Corporation (DRE)":["DRE","Duke"],
    "Dun & Bradstreet Holdings Inc. (DNB)":["DNB","Dun"],
    "Dycom Industries Inc. (DY)":["DY","Dycom"],
    "Dynatrace Inc. (DT)":["DT","Dynatrace"],
    "Eagle Materials Inc (EXP)":["EXP","Eagle"],
    "Eargo Inc. (EAR)":["EAR","Eargo"],
    "East West Bancorp Inc. (EWBC)":["EWBC","East"],
    "Eastern Bankshares Inc. (EBC)":["EBC","Eastern"],
    "EastGroup Properties Inc. (EGP)":["EGP","EastGroup"],
    "Eastman Chemical Company (EMN)":["EMN","Eastman"],
    "Eaton Vance Tax-Managed Global Diversified Equity Income Fund Eaton Vance Tax-Managed Global Diversified Equity Income Fund of Beneficial Interest (EXG)":["EXG","Eaton"],
    "eBay Inc. (EBAY)":["EBAY","eBay"],
    "EchoStar Corporation (SATS)":["SATS","EchoStar"],
    "Ecolab Inc. (ECL)":["ECL","Ecolab"],
    "Edison International (EIX)":["EIX","Edison"],
    "Editas Medicine Inc. (EDIT)":["EDIT","Editas"],
    "Edwards Lifesciences Corporation (EW)":["EW","Edwards"],
    "Elanco Animal Health Incorporated (ELAN)":["ELAN","Elanco"],
    "Elastic N.V. (ESTC)":["ESTC","Elastic"],
    "Electronic Arts Inc. (EA)":["EA","Electronic"],
    "Element Solutions Inc. (ESI)":["ESI","Element"],
    "Eli Lilly and Company (LLY)":["LLY","Eli"],
    "EMCOR Group Inc. (EME)":["EME","EMCOR"],
    "Emergent Biosolutions Inc. (EBS)":["EBS","Emergent"],
    "Emerson Electric Company (EMR)":["EMR","Emerson"],
    "Empire State Realty Trust Inc. (ESRT)":["ESRT","Empire"],
    "Enbridge Inc (ENB)":["ENB","Enbridge"],
    "Encompass Health Corporation (EHC)":["EHC","Encompass"],
    "Energizer Holdings Inc. (ENR)":["ENR","Energizer"],
    "Energy Transfer LP (ET)":["ET","Energy"],
    "EnerSys (ENS)":["ENS","EnerSys"],
    "Enphase Energy Inc. (ENPH)":["ENPH","Enphase"],
    "Entegris Inc. (ENTG)":["ENTG","Entegris"],
    "Entergy Corporation (ETR)":["ETR","Entergy"],
    "Enterprise Products Partners L.P. (EPD)":["EPD","Enterprise"],
    "Envestnet Inc (ENV)":["ENV","Envestnet"],
    "EOG Resources Inc. (EOG)":["EOG","EOG"],
    "EPAM Systems Inc. (EPAM)":["EPAM","EPAM"],
    "EPR Properties (EPR)":["EPR","EPR"],
    "EQT Corporation (EQT)":["EQT","EQT"],
    "Equifax Inc. (EFX)":["EFX","Equifax"],
    "Equinix Inc. REIT (EQIX)":["EQIX","Equinix"],
    "Equitable Holdings Inc. (EQH)":["EQH","Equitable"],
    "Equity Commonwealth of Beneficial Interest (EQC)":["EQC","Equity"],
    "Equity Lifestyle Properties Inc. (ELS)":["ELS","Equity"],
    "Equity Residential of Beneficial Interest (EQR)":["EQR","Equity"],
    "Erie Indemnity Company (ERIE)":["ERIE","Erie"],
    "ESCO Technologies Inc. (ESE)":["ESE","ESCO"],
    "Essential Properties Realty Trust Inc. (EPRT)":["EPRT","Essential"],
    "Essential Utilities Inc. (WTRG)":["WTRG","Essential"],
    "Essex Property Trust Inc. (ESS)":["ESS","Essex"],
    "Estee Lauder Companies Inc. (EL)":["EL","Estee"],
    "Etsy Inc. (ETSY)":["ETSY","Etsy"],
    "Euronet Worldwide Inc. (EEFT)":["EEFT","Euronet"],
    "Eventbrite Inc. (EB)":["EB","Eventbrite"],
    "Everbridge Inc. (EVBG)":["EVBG","Everbridge"],
    "Evercore Inc. (EVR)":["EVR","Evercore"],
    "Eversource Energy (ES)":["ES","Eversource"],
    "Evoqua Water Technologies Corp. (AQUA)":["AQUA","Evoqua"],
    "Exact Sciences Corporation (EXAS)":["EXAS","Exact"],
    "Exelixis Inc. (EXEL)":["EXEL","Exelixis"],
    "Exelon Corporation (EXC)":["EXC","Exelon"],
    "ExlService Holdings Inc. (EXLS)":["EXLS","ExlService"],
    "eXp World Holdings Inc. (EXPI)":["EXPI","eXp"],
    "Expedia Group Inc. (EXPE)":["EXPE","Expedia"],
    "Expeditors International of Washington Inc. (EXPD)":["EXPD","Expeditors"],
    "Exponent Inc. (EXPO)":["EXPO","Exponent"],
    "Extended Stay America Inc. Paired Shares (STAY)":["STAY","Extended"],
    "Extra Space Storage Inc (EXR)":["EXR","Extra"],
    "Exxon Mobil Corporation (XOM)":["XOM","Exxon"],
    "F.N.B. Corporation (FNB)":["FNB","F.N.B."],
    "F5 Networks Inc. (FFIV)":["FFIV","F5"],
    "Facebook Inc. (FB)":["FB","Facebook"],
    "Fair Isaac Corproation (FICO)":["FICO","Fair"],
    "Fastenal Company (FAST)":["FAST","Fastenal"],
    "Fate Therapeutics Inc. (FATE)":["FATE","Fate"],
    "FB Financial Corporation (FBK)":["FBK","FB"],
    "Federal Realty Investment Trust (FRT)":["FRT","Federal"],
    "Federal Signal Corporation (FSS)":["FSS","Federal"],
    "Federated Hermes Inc. (FHI)":["FHI","Federated"],
    "FedEx Corporation (FDX)":["FDX","FedEx"],
    "FibroGen Inc (FGEN)":["FGEN","FibroGen"],
    "Fidelity National Information Services Inc. (FIS)":["FIS","Fidelity"],
    "Fifth Third Bancorp (FITB)":["FITB","Fifth"],
    "FinVolution Group American Depositary Shares (FINV)":["FINV","FinVolution"],
    "FireEye Inc. (FEYE)":["FEYE","FireEye"],
    "First American Corporation (FAF)":["FAF","First"],
    "First Citizens BancShares Inc. (FCNCA)":["FCNCA","First"],
    "First Financial Bancorp. (FFBC)":["FFBC","First"],
    "First Financial Bankshares Inc. (FFIN)":["FFIN","First"],
    "First Hawaiian Inc. (FHB)":["FHB","First"],
    "First Horizon Corporation (FHN)":["FHN","First"],
    "First Industrial Realty Trust Inc. (FR)":["FR","First"],
    "First Interstate BancSystem Inc. (FIBK)":["FIBK","First"],
    "First Majestic Silver Corp. (AG)":["AG","First"],
    "First Merchants Corporation (FRME)":["FRME","First"],
    "First Midwest Bancorp Inc. (FMBI)":["FMBI","First"],
    "FIRST REPUBLIC BANK (FRC)":["FRC","FIRST"],
    "First Solar Inc. (FSLR)":["FSLR","First"],
    "FirstCash Inc. (FCFS)":["FCFS","FirstCash"],
    "FirstEnergy Corp. (FE)":["FE","FirstEnergy"],
    "FirstService Corporation (FSV)":["FSV","FirstService"],
    "Fiserv Inc. (FISV)":["FISV","Fiserv"],
    "Five Below Inc. (FIVE)":["FIVE","Five"],
    "Five9 Inc. (FIVN)":["FIVN","Five9"],
    "Flagstar Bancorp Inc. (FBC)":["FBC","Flagstar"],
    "FleetCor Technologies Inc. (FLT)":["FLT","FleetCor"],
    "FLIR Systems Inc. (FLIR)":["FLIR","FLIR"],
    "Flowers Foods Inc. (FLO)":["FLO","Flowers"],
    "Flowserve Corporation (FLS)":["FLS","Flowserve"],
    "Fluor Corporation (FLR)":["FLR","Fluor"],
    "FMC Corporation (FMC)":["FMC","FMC"],
    "FNF Group of Fidelity National Financial Inc. (FNF)":["FNF","FNF"],
    "Focus Financial Partners Inc. (FOCS)":["FOCS","Focus"],
    "Fomento Economico Mexicano S.A.B. de C.V. (FMX)":["FMX","Fomento"],
    "Foot Locker Inc. (FL)":["FL","Foot"],
    "Ford Motor Company (F)":["F","Ford"],
    "FormFactor Inc. FormFactor Inc. (FORM)":["FORM","FormFactor"],
    "Fortinet Inc. (FTNT)":["FTNT","Fortinet"],
    "Fortress Transportation and Infrastructure Investors LLC (FTAI)":["FTAI","Fortress"],
    "Fortune Brands Home & Security Inc. (FBHS)":["FBHS","Fortune"],
    "Forward Air Corporation (FWRD)":["FWRD","Forward"],
    "Four Corners Property Trust Inc. (FCPT)":["FCPT","Four"],
    "Fox Corporation (FOX)":["FOX","Fox"],
    "Fox Corporation (FOXA)":["FOXA","Fox"],
    "Fox Factory Holding Corp. (FOXF)":["FOXF","Fox"],
    "Franco-Nevada Corporation (FNV)":["FNV","Franco-Nevada"],
    "Franklin Electric Co. Inc. (FELE)":["FELE","Franklin"],
    "Franklin Resources Inc. (BEN)":["BEN","Franklin"],
    "Freeport-McMoRan Inc. (FCX)":["FCX","Freeport-McMoRan"],
    "Freshpet Inc. (FRPT)":["FRPT","Freshpet"],
    "frontdoor inc. (FTDR)":["FTDR","frontdoor"],
    "Frontier Group Holdings Inc. (ULCC)":["ULCC","Frontier"],
    "FTI Consulting Inc. (FCN)":["FCN","FTI"],
    "FuelCell Energy Inc. (FCEL)":["FCEL","FuelCell"],
    "Fulgent Genetics Inc. (FLGT)":["FLGT","Fulgent"],
    "Fulton Financial Corporation (FULT)":["FULT","Fulton"],
    "Gabelli Dividend & Income Trust of Beneficial Interest (GDV)":["GDV","Gabelli"],
    "GameStop Corporation (GME)":["GME","GameStop"],
    "Gaming and Leisure Properties Inc. (GLPI)":["GLPI","Gaming"],
    "Gap Inc. (GPS)":["GPS","Gap"],
    "Gartner Inc. (IT)":["IT","Gartner"],
    "GATX Corporation (GATX)":["GATX","GATX"],
    "GCM Grosvenor Inc. (GCMG)":["GCMG","GCM"],
    "Generac Holdlings Inc. (GNRC)":["GNRC","Generac"],
    "General Dynamics Corporation (GD)":["GD","General"],
    "General Electric Company (GE)":["GE","General"],
    "General Mills Inc. (GIS)":["GIS","General"],
    "General Motors Company (GM)":["GM","General"],
    "Gentex Corporation (GNTX)":["GNTX","Gentex"],
    "Gentherm Inc (THRM)":["THRM","Gentherm"],
    "Genuine Parts Company (GPC)":["GPC","Genuine"],
    "Gibraltar Industries Inc. (ROCK)":["ROCK","Gibraltar"],
    "Gildan Activewear Inc. Sub. Vot. (GIL)":["GIL","Gildan"],
    "Gilead Sciences Inc. (GILD)":["GILD","Gilead"],
    "Glacier Bancorp Inc. (GBCI)":["GBCI","Glacier"],
    "Glaukos Corporation (GKOS)":["GKOS","Glaukos"],
    "Global Blood Therapeutics Inc. (GBT)":["GBT","Global"],
    "Global Payments Inc. (GPN)":["GPN","Global"],
    "Globe Life Inc. (GL)":["GL","Globe"],
    "Globus Medical Inc. (GMED)":["GMED","Globus"],
    "Glu Mobile Inc. (GLUU)":["GLUU","Glu"],
    "GoDaddy Inc. (GDDY)":["GDDY","GoDaddy"],
    "GoHealth Inc. (GOCO)":["GOCO","GoHealth"],
    "Goldman Sachs BDC Inc. (GSBD)":["GSBD","Goldman"],
    "Goldman Sachs Group Inc. (GS)":["GS","Goldman"],
    "Golub Capital BDC Inc. (GBDC)":["GBDC","Golub"],
    "GoodRx Holdings Inc. (GDRX)":["GDRX","GoodRx"],
    "Goosehead Insurance Inc. (GSHD)":["GSHD","Goosehead"],
    "Graco Inc. (GGG)":["GGG","Graco"],
    "GrafTech International Ltd. (EAF)":["EAF","GrafTech"],
    "Graham Holdings Company (GHC)":["GHC","Graham"],
    "Grand Canyon Education Inc. (LOPE)":["LOPE","Grand"],
    "Graphic Packaging Holding Company (GPK)":["GPK","Graphic"],
    "Green Dot Corporation $0.001 par value (GDOT)":["GDOT","Green"],
    "Greif Inc. (GEF)":["GEF","Greif"],
    "Grocery Outlet Holding Corp. (GO)":["GO","Grocery"],
    "Group 1 Automotive Inc. (GPI)":["GPI","Group"],
    "GrowGeneration Corp. (GRWG)":["GRWG","GrowGeneration"],
    "Grupo Aeroportuario del Centro Norte S.A.B. de C.V. ADS (OMAB)":["OMAB","Grupo"],
    "Grupo Aeroportuario Del Pacifico S.A. B. de C.V. Grupo Aeroportuario Del Pacifico S.A. de C.V. (PAC)":["PAC","Grupo"],
    "Grupo Aeroportuario del Sureste S.A. de C.V. (ASR)":["ASR","Grupo"],
    "Grupo Televisa S.A. (TV)":["TV","Grupo"],
    "Guardant Health Inc. (GH)":["GH","Guardant"],
    "Guidewire Software Inc. (GWRE)":["GWRE","Guidewire"],
    "H. B. Fuller Company (FUL)":["FUL","H."],
    "H&R Block Inc. (HRB)":["HRB","H&R"],
    "Haemonetics Corporation (HAE)":["HAE","Haemonetics"],
    "Hain Celestial Group Inc. (HAIN)":["HAIN","Hain"],
    "Halliburton Company (HAL)":["HAL","Halliburton"],
    "Halozyme Therapeutics Inc. (HALO)":["HALO","Halozyme"],
    "Hamilton Lane Incorporated (HLNE)":["HLNE","Hamilton"],
    "Hancock Whitney Corporation (HWC)":["HWC","Hancock"],
    "Hanesbrands Inc. (HBI)":["HBI","Hanesbrands"],
    "Hannon Armstrong Sustainable Infrastructure Capital Inc. (HASI)":["HASI","Hannon"],
    "Hanover Insurance Group Inc (THG)":["THG","Hanover"],
    "Harley-Davidson Inc. (HOG)":["HOG","Harley-Davidson"],
    "Hartford Financial Services Group Inc. (HIG)":["HIG","Hartford"],
    "Hasbro Inc. (HAS)":["HAS","Hasbro"],
    "Hawaiian Electric Industries Inc. (HE)":["HE","Hawaiian"],
    "HCA Healthcare Inc. (HCA)":["HCA","HCA"],
    "Health Catalyst Inc (HCAT)":["HCAT","Health"],
    "Healthcare Realty Trust Incorporated (HR)":["HR","Healthcare"],
    "Healthcare Services Group Inc. (HCSG)":["HCSG","Healthcare"],
    "Healthcare Trust of America Inc. (HTA)":["HTA","Healthcare"],
    "HealthEquity Inc. (HQY)":["HQY","HealthEquity"],
    "Healthpeak Properties Inc. (PEAK)":["PEAK","Healthpeak"],
    "Heartland Financial USA Inc. (HTLF)":["HTLF","Heartland"],
    "Hecla Mining Company (HL)":["HL","Hecla"],
    "Heico Corporation (HEI)":["HEI","Heico"],
    "Helios Technologies Inc. (HLIO)":["HLIO","Helios"],
    "Helmerich & Payne Inc. (HP)":["HP","Helmerich"],
    "Henry Schein Inc. (HSIC)":["HSIC","Henry"],
    "Herman Miller Inc. (MLHR)":["MLHR","Herman"],
    "Hess Corporation (HES)":["HES","Hess"],
    "Hewlett Packard Enterprise Company (HPE)":["HPE","Hewlett"],
    "Hexcel Corporation (HXL)":["HXL","Hexcel"],
    "Highwoods Properties Inc. (HIW)":["HIW","Highwoods"],
    "Hill-Rom Holdings Inc (HRC)":["HRC","Hill-Rom"],
    "Hillenbrand Inc (HI)":["HI","Hillenbrand"],
    "Hilltop Holdings Inc. (HTH)":["HTH","Hilltop"],
    "Holly Energy Partners L.P. (HEP)":["HEP","Holly"],
    "HollyFrontier Corporation (HFC)":["HFC","HollyFrontier"],
    "Hologic Inc. (HOLX)":["HOLX","Hologic"],
    "Home BancShares Inc. (HOMB)":["HOMB","Home"],
    "Home Depot Inc. (HD)":["HD","Home"],
    "Honeywell International Inc. (HON)":["HON","Honeywell"],
    "Hormel Foods Corporation (HRL)":["HRL","Hormel"],
    "Host Hotels & Resorts Inc. (HST)":["HST","Host"],
    "Houlihan Lokey Inc. (HLI)":["HLI","Houlihan"],
    "Howard Hughes Corporation (HHC)":["HHC","Howard"],
    "Howmet Aerospace Inc. (HWM)":["HWM","Howmet"],
    "HP Inc. (HPQ)":["HPQ","HP"],
    "Hub Group Inc. (HUBG)":["HUBG","Hub"],
    "Hubbell Inc (HUBB)":["HUBB","Hubbell"],
    "HubSpot Inc. (HUBS)":["HUBS","HubSpot"],
    "Hudbay Minerals Inc. (HBM)":["HBM","Hudbay"],
    "Hudson Pacific Properties Inc. (HPP)":["HPP","Hudson"],
    "Humana Inc. (HUM)":["HUM","Humana"],
    "Huntington Bancshares Incorporated (HBAN)":["HBAN","Huntington"],
    "Huntington Ingalls Industries Inc. (HII)":["HII","Huntington"],
    "Huntsman Corporation (HUN)":["HUN","Huntsman"],
    "HUYA Inc. (HUYA)":["HUYA","HUYA"],
    "Hyatt Hotels Corporation (H)":["H","Hyatt"],
    "IAC/InterActiveCorp (IAC)":["IAC","IAC/InterActiveCorp"],
    "Icahn Enterprises L.P. (IEP)":["IEP","Icahn"],
    "ICU Medical Inc. (ICUI)":["ICUI","ICU"],
    "IDACORP Inc. (IDA)":["IDA","IDACORP"],
    "IDEX Corporation (IEX)":["IEX","IDEX"],
    "IDEXX Laboratories Inc. (IDXX)":["IDXX","IDEXX"],
    "IGM Biosciences Inc. (IGMS)":["IGMS","IGM"],
    "iHeartMedia Inc. (IHRT)":["IHRT","iHeartMedia"],
    "II-VI Incorporated (IIVI)":["IIVI","II-VI"],
    "Illinois Tool Works Inc. (ITW)":["ITW","Illinois"],
    "Illumina Inc. (ILMN)":["ILMN","Illumina"],
    "ImmunityBio Inc. (IBRX)":["IBRX","ImmunityBio"],
    "Inari Medical Inc. (NARI)":["NARI","Inari"],
    "Incyte Corp. (INCY)":["INCY","Incyte"],
    "Independent Bank Corp. (INDB)":["INDB","Independent"],
    "Independent Bank Group Inc (IBTX)":["IBTX","Independent"],
    "Industrias Bachoco S.A.B. de C.V. (IBA)":["IBA","Industrias"],
    "Infinera Corporation (INFN)":["INFN","Infinera"],
    "Ingersoll Rand Inc. (IR)":["IR","Ingersoll"],
    "Ingredion Incorporated (INGR)":["INGR","Ingredion"],
    "Innospec Inc. (IOSP)":["IOSP","Innospec"],
    "InnovAge Holding Corp. (INNV)":["INNV","InnovAge"],
    "Innovative Industrial Properties Inc. (IIPR)":["IIPR","Innovative"],
    "Inovalon Holdings Inc. (INOV)":["INOV","Inovalon"],
    "Inphi Corporation (IPHI)":["IPHI","Inphi"],
    "Insight Enterprises Inc. (NSIT)":["NSIT","Insight"],
    "Insmed Inc. (INSM)":["INSM","Insmed"],
    "Insperity Inc. (NSP)":["NSP","Insperity"],
    "Inspire Medical Systems Inc. (INSP)":["INSP","Inspire"],
    "Instil Bio Inc. (TIL)":["TIL","Instil"],
    "Insulet Corporation (PODD)":["PODD","Insulet"],
    "Integer Holdings Corporation (ITGR)":["ITGR","Integer"],
    "Integra LifeSciences Holdings Corporation (IART)":["IART","Integra"],
    "Intel Corporation (INTC)":["INTC","Intel"],
    "Intellia Therapeutics Inc. (NTLA)":["NTLA","Intellia"],
    "Inter Parfums Inc. (IPAR)":["IPAR","Inter"],
    "Interactive Brokers Group Inc. (IBKR)":["IBKR","Interactive"],
    "Intercontinental Exchange Inc. (ICE)":["ICE","Intercontinental"],
    "InterDigital Inc. (IDCC)":["IDCC","InterDigital"],
    "Internationa Flavors & Fragrances Inc. (IFF)":["IFF","Internationa"],
    "International Bancshares Corporation (IBOC)":["IBOC","International"],
    "International Business Machines Corporation (IBM)":["IBM","International"],
    "International Game Technology (IGT)":["IGT","International"],
    "International Paper Company (IP)":["IP","International"],
    "Interpublic Group of Companies Inc. (IPG)":["IPG","Interpublic"],
    "Intra-Cellular Therapies Inc. (ITCI)":["ITCI","Intra-Cellular"],
    "Intuit Inc. (INTU)":["INTU","Intuit"],
    "Intuitive Surgical Inc. (ISRG)":["ISRG","Intuitive"],
    "Invesco Ltd (IVZ)":["IVZ","Invesco"],
    "Investors Bancorp Inc. (ISBC)":["ISBC","Investors"],
    "Invitae Corporation (NVTA)":["NVTA","Invitae"],
    "Invitation Homes Inc. (INVH)":["INVH","Invitation"],
    "Ionis Pharmaceuticals Inc. (IONS)":["IONS","Ionis"],
    "Iovance Biotherapeutics Inc. (IOVA)":["IOVA","Iovance"],
    "IPG Photonics Corporation (IPGP)":["IPGP","IPG"],
    "IQVIA Holdings Inc. (IQV)":["IQV","IQVIA"],
    "iRhythm Technologies Inc. (IRTC)":["IRTC","iRhythm"],
    "Iridium Communications Inc (IRDM)":["IRDM","Iridium"],
    "iRobot Corporation (IRBT)":["IRBT","iRobot"],
    "Iron Mountain Incorporated (IRM)":["IRM","Iron"],
    "Itron Inc. (ITRI)":["ITRI","Itron"],
    "ITT Inc. (ITT)":["ITT","ITT"],
    "J & J Snack Foods Corp. (JJSF)":["JJSF","J"],
    "J.B. Hunt Transport Services Inc. (JBHT)":["JBHT","J.B."],
    "J.M. Smucker Company (SJM)":["SJM","J.M."],
    "j2 Global Inc. (JCOM)":["JCOM","j2"],
    "Jabil Inc. (JBL)":["JBL","Jabil"],
    "Jack Henry & Associates Inc. (JKHY)":["JKHY","Jack"],
    "Jack In The Box Inc. (JACK)":["JACK","Jack"],
    "Jacobs Engineering Group Inc. (J)":["J","Jacobs"],
    "Jamf Holding Corp. (JAMF)":["JAMF","Jamf"],
    "JBG SMITH Properties (JBGS)":["JBGS","JBG"],
    "Jefferies Financial Group Inc. (JEF)":["JEF","Jefferies"],
    "JELD-WEN Holding Inc. (JELD)":["JELD","JELD-WEN"],
    "JetBlue Airways Corporation (JBLU)":["JBLU","JetBlue"],
    "JFrog Ltd. (FROG)":["FROG","JFrog"],
    "John Bean Technologies Corporation (JBT)":["JBT","John"],
    "Johnson & Johnson (JNJ)":["JNJ","Johnson"],
    "Jones Lang LaSalle Incorporated (JLL)":["JLL","Jones"],
    "JP Morgan Chase & Co. (JPM)":["JPM","JP"],
    "Juniper Networks Inc. (JNPR)":["JNPR","Juniper"],
    "Kadant Inc (KAI)":["KAI","Kadant"],
    "Kansas City Southern (KSU)":["KSU","Kansas"],
    "Karuna Therapeutics Inc. (KRTX)":["KRTX","Karuna"],
    "KB Home (KBH)":["KBH","KB"],
    "KBR Inc. (KBR)":["KBR","KBR"],
    "Kellogg Company (K)":["K","Kellogg"],
    "Kemper Corporation (KMPR)":["KMPR","Kemper"],
    "Kennametal Inc. (KMT)":["KMT","Kennametal"],
    "Kennedy-Wilson Holdings Inc. (KW)":["KW","Kennedy-Wilson"],
    "Keurig Dr Pepper Inc. (KDP)":["KDP","Keurig"],
    "KeyCorp (KEY)":["KEY","KeyCorp"],
    "Keysight Technologies Inc. (KEYS)":["KEYS","Keysight"],
    "Kilroy Realty Corporation (KRC)":["KRC","Kilroy"],
    "Kimberly-Clark Corporation (KMB)":["KMB","Kimberly-Clark"],
    "Kimco Realty Corporation (KIM)":["KIM","Kimco"],
    "Kinder Morgan Inc. (KMI)":["KMI","Kinder"],
    "Kinross Gold Corporation (KGC)":["KGC","Kinross"],
    "Kinsale Capital Group Inc. (KNSL)":["KNSL","Kinsale"],
    "Kirby Corporation (KEX)":["KEX","Kirby"],
    "KKR & Co. Inc. (KKR)":["KKR","KKR"],
    "KLA Corporation (KLAC)":["KLAC","KLA"],
    "Knight-Swift Transportation Holdings Inc. (KNX)":["KNX","Knight-Swift"],
    "Kodiak Sciences Inc (KOD)":["KOD","Kodiak"],
    "Kohl's Corporation (KSS)":["KSS","Kohl's"],
    "Korn Ferry (KFY)":["KFY","Korn"],
    "Kratos Defense & Security Solutions Inc. (KTOS)":["KTOS","Kratos"],
    "Kroger Company (KR)":["KR","Kroger"],
    "L Brands Inc. (LB)":["LB","L"],
    "L3Harris Technologies Inc. (LHX)":["LHX","L3Harris"],
    "Laboratory Corporation of America Holdings (LH)":["LH","Laboratory"],
    "Lam Research Corporation (LRCX)":["LRCX","Lam"],
    "Lamar Advertising Company (LAMR)":["LAMR","Lamar"],
    "Lancaster Colony Corporation (LANC)":["LANC","Lancaster"],
    "Landstar System Inc. (LSTR)":["LSTR","Landstar"],
    "Las Vegas Sands Corp. (LVS)":["LVS","Las"],
    "Lattice Semiconductor Corporation (LSCC)":["LSCC","Lattice"],
    "Laureate Education Inc. (LAUR)":["LAUR","Laureate"],
    "LCI Industries (LCII)":["LCII","LCI"],
    "Lear Corporation (LEA)":["LEA","Lear"],
    "Legend Biotech Corporation American Depositary Shares (LEGN)":["LEGN","Legend"],
    "Leggett & Platt Incorporated (LEG)":["LEG","Leggett"],
    "Leidos Holdings Inc. (LDOS)":["LDOS","Leidos"],
    "Lemonade Inc. (LMND)":["LMND","Lemonade"],
    "LendingTree Inc. (TREE)":["TREE","LendingTree"],
    "Lennar Corporation (LEN)":["LEN","Lennar"],
    "Lennox International Inc. (LII)":["LII","Lennox"],
    "Leslie's Inc. (LESL)":["LESL","Leslie's"],
    "Levi Strauss & Co (LEVI)":["LEVI","Levi"],
    "Lexington Realty Trust (LXP)":["LXP","Lexington"],
    "LGI Homes Inc. (LGIH)":["LGIH","LGI"],
    "LHC Group (LHCG)":["LHCG","LHC"],
    "Liberty Broadband Corporation (LBRDA)":["LBRDA","Liberty"],
    "Liberty Broadband Corporation (LBRDK)":["LBRDK","Liberty"],
    "Liberty Latin America Ltd. (LILA)":["LILA","Liberty"],
    "Liberty Latin America Ltd. (LILAK)":["LILAK","Liberty"],
    "Liberty Media Corporation Series A Liberty Formula One (FWONA)":["FWONA","Liberty"],
    "Liberty Media Corporation Series A Liberty SiriusXM (LSXMA)":["LSXMA","Liberty"],
    "Liberty Media Corporation Series B Liberty SiriusXM (LSXMB)":["LSXMB","Liberty"],
    "Liberty Media Corporation Series C Liberty Formula One (FWONK)":["FWONK","Liberty"],
    "Liberty Media Corporation Series C Liberty SiriusXM (LSXMK)":["LSXMK","Liberty"],
    "Liberty Oilfield Services Inc. (LBRT)":["LBRT","Liberty"],
    "Liberty TripAdvisor Holdings Inc. Series B (LTRPB)":["LTRPB","Liberty"],
    "Life Storage Inc. (LSI)":["LSI","Life"],
    "Ligand Pharmaceuticals Incorporated (LGND)":["LGND","Ligand"],
    "Lincoln Electric Holdings Inc. (LECO)":["LECO","Lincoln"],
    "Lincoln National Corporation (LNC)":["LNC","Lincoln"],
    "Lithia Motors Inc. (LAD)":["LAD","Lithia"],
    "Littelfuse Inc. (LFUS)":["LFUS","Littelfuse"],
    "Live Nation Entertainment Inc. (LYV)":["LYV","Live"],
    "Live Oak Bancshares Inc. (LOB)":["LOB","Live"],
    "Livent Corporation (LTHM)":["LTHM","Livent"],
    "LivePerson Inc. (LPSN)":["LPSN","LivePerson"],
    "LiveRamp Holdings Inc. (RAMP)":["RAMP","LiveRamp"],
    "LKQ Corporation (LKQ)":["LKQ","LKQ"],
    "Lockheed Martin Corporation (LMT)":["LMT","Lockheed"],
    "Loews Corporation (L)":["L","Loews"],
    "Logitech International S.A. (LOGI)":["LOGI","Logitech"],
    "Lordstown Motors Corp. (RIDE)":["RIDE","Lordstown"],
    "Louisiana-Pacific Corporation (LPX)":["LPX","Louisiana-Pacific"],
    "Lowe's Companies Inc. (LOW)":["LOW","Lowe's"],
    "LPL Financial Holdings Inc. (LPLA)":["LPLA","LPL"],
    "lululemon athletica inc. (LULU)":["LULU","lululemon"],
    "Lumen Technologies Inc. (LUMN)":["LUMN","Lumen"],
    "Lumentum Holdings Inc. (LITE)":["LITE","Lumentum"],
    "Luminar Technologies Inc. (LAZR)":["LAZR","Luminar"],
    "Lyft Inc. (LYFT)":["LYFT","Lyft"],
    "M.D.C. Holdings Inc. (MDC)":["MDC","M.D.C."],
    "M&T Bank Corporation (MTB)":["MTB","M&T"],
    "Macerich Company (MAC)":["MAC","Macerich"],
    "MACOM Technology Solutions Holdings Inc. (MTSI)":["MTSI","MACOM"],
    "Macquarie Infrastructure Corporation (MIC)":["MIC","Macquarie"],
    "Macy's Inc (M)":["M","Macy's"],
    "Madison Square Garden Sports Corp. (MSGS)":["MSGS","Madison"],
    "Magellan Health Inc. (MGLN)":["MGLN","Magellan"],
    "Magellan Midstream Partners L.P. Limited Partnership (MMP)":["MMP","Magellan"],
    "Magna International Inc. (MGA)":["MGA","Magna"],
    "Magnite Inc. (MGNI)":["MGNI","Magnite"],
    "Magnolia Oil & Gas Corporation (MGY)":["MGY","Magnolia"],
    "Main Street Capital Corporation (MAIN)":["MAIN","Main"],
    "Manhattan Associates Inc. (MANH)":["MANH","Manhattan"],
    "ManpowerGroup (MAN)":["MAN","ManpowerGroup"],
    "ManTech International Corporation $0.01 Par Value (MANT)":["MANT","ManTech"],
    "Manulife Financial Corporation (MFC)":["MFC","Manulife"],
    "Marathon Digital Holdings Inc. (MARA)":["MARA","Marathon"],
    "Marathon Oil Corporation (MRO)":["MRO","Marathon"],
    "Marathon Petroleum Corporation (MPC)":["MPC","Marathon"],
    "Maravai LifeSciences Holdings Inc. (MRVI)":["MRVI","Maravai"],
    "Markel Corporation (MKL)":["MKL","Markel"],
    "MarketAxess Holdings Inc. (MKTX)":["MKTX","MarketAxess"],
    "Marriott International (MAR)":["MAR","Marriott"],
    "Marriott Vacations Worldwide Corporation (VAC)":["VAC","Marriott"],
    "Marsh & McLennan Companies Inc. (MMC)":["MMC","Marsh"],
    "Martin Marietta Materials Inc. (MLM)":["MLM","Martin"],
    "Masco Corporation (MAS)":["MAS","Masco"],
    "Masimo Corporation (MASI)":["MASI","Masimo"],
    "Masonite International Corporation (DOOR)":["DOOR","Masonite"],
    "MasTec Inc. (MTZ)":["MTZ","MasTec"],
    "Mastercard Incorporated (MA)":["MA","Mastercard"],
    "Matador Resources Company (MTDR)":["MTDR","Matador"],
    "Match Group Inc. (MTCH)":["MTCH","Match"],
    "Matson Inc. (MATX)":["MATX","Matson"],
    "Mattel Inc. (MAT)":["MAT","Mattel"],
    "Maxim Integrated Products Inc. (MXIM)":["MXIM","Maxim"],
    "Maximus Inc. (MMS)":["MMS","Maximus"],
    "MaxLinear Inc. (MXL)":["MXL","MaxLinear"],
    "McAfee Corp. (MCFE)":["MCFE","McAfee"],
    "McCormick & Company Incorporated (MKC)":["MKC","McCormick"],
    "McDonald's Corporation (MCD)":["MCD","McDonald's"],
    "McKesson Corporation (MCK)":["MCK","McKesson"],
    "MDU Resources Group Inc. (MDU)":["MDU","MDU"],
    "Medallia Inc. (MDLA)":["MDLA","Medallia"],
    "Medical Properties Trust Inc. (MPW)":["MPW","Medical"],
    "MEDIFAST INC (MED)":["MED","MEDIFAST"],
    "Mednax Inc. (MD)":["MD","Mednax"],
    "Medpace Holdings Inc. (MEDP)":["MEDP","Medpace"],
    "Medtronic plc. (MDT)":["MDT","Medtronic"],
    "Merck & Company Inc. (MRK)":["MRK","Merck"],
    "Mercury General Corporation (MCY)":["MCY","Mercury"],
    "Mercury Systems Inc (MRCY)":["MRCY","Mercury"],
    "Merit Medical Systems Inc. (MMSI)":["MMSI","Merit"],
    "Meritage Homes Corporation (MTH)":["MTH","Meritage"],
    "Meritor Inc. (MTOR)":["MTOR","Meritor"],
    "Methanex Corporation (MEOH)":["MEOH","Methanex"],
    "MetLife Inc. (MET)":["MET","MetLife"],
    "MGE Energy Inc (MGEE)":["MGEE","MGE"],
    "MGIC Investment Corporation (MTG)":["MTG","MGIC"],
    "MGM Growth Properties LLC (MGP)":["MGP","MGM"],
    "MGM Resorts International (MGM)":["MGM","MGM"],
    "Microchip Technology Incorporated (MCHP)":["MCHP","Microchip"],
    "Micron Technology Inc. (MU)":["MU","Micron"],
    "Microsoft Corporation (MSFT)":["MSFT","Microsoft"],
    "MicroStrategy Incorporated (MSTR)":["MSTR","MicroStrategy"],
    "MicroVision Inc. (MVIS)":["MVIS","MicroVision"],
    "Mid-America Apartment Communities Inc. (MAA)":["MAA","Mid-America"],
    "Middleby Corporation (MIDD)":["MIDD","Middleby"],
    "Minerals Technologies Inc. (MTX)":["MTX","Minerals"],
    "Mirati Therapeutics Inc. (MRTX)":["MRTX","Mirati"],
    "MKS Instruments Inc. (MKSI)":["MKSI","MKS"],
    "Moderna Inc. (MRNA)":["MRNA","Moderna"],
    "ModivCare Inc. (MODV)":["MODV","ModivCare"],
    "Mohawk Industries Inc. (MHK)":["MHK","Mohawk"],
    "Molina Healthcare Inc (MOH)":["MOH","Molina"],
    "Molson Coors Beverage Company (TAP)":["TAP","Molson"],
    "Mondelez International Inc. (MDLZ)":["MDLZ","Mondelez"],
    "MongoDB Inc. (MDB)":["MDB","MongoDB"],
    "Monolithic Power Systems Inc. (MPWR)":["MPWR","Monolithic"],
    "Monro Inc. (MNRO)":["MNRO","Monro"],
    "Monster Beverage Corporation (MNST)":["MNST","Monster"],
    "Moody's Corporation (MCO)":["MCO","Moody's"],
    "Morgan Stanley (MS)":["MS","Morgan"],
    "Morningstar Inc. (MORN)":["MORN","Morningstar"],
    "Morphic Holding Inc. (MORF)":["MORF","Morphic"],
    "Mosaic Company (MOS)":["MOS","Mosaic"],
    "Motorola Solutions Inc. (MSI)":["MSI","Motorola"],
    "MPLX LP (MPLX)":["MPLX","MPLX"],
    "Mr. Cooper Group Inc. (COOP)":["COOP","Mr."],
    "MSA Safety Incorporated (MSA)":["MSA","MSA"],
    "MSC Industrial Direct Company Inc. (MSM)":["MSM","MSC"],
    "MSCI Inc (MSCI)":["MSCI","MSCI"],
    "Mueller Industries Inc. (MLI)":["MLI","Mueller"],
    "MUELLER WATER PRODUCTS (MWA)":["MWA","MUELLER"],
    "Murphy Oil Corporation (MUR)":["MUR","Murphy"],
    "Murphy USA Inc. (MUSA)":["MUSA","Murphy"],
    "Myriad Genetics Inc. (MYGN)":["MYGN","Myriad"],
    "NanoString Technologies Inc. (NSTG)":["NSTG","NanoString"],
    "Nasdaq Inc. (NDAQ)":["NDAQ","Nasdaq"],
    "Natera Inc. (NTRA)":["NTRA","Natera"],
    "National Beverage Corp. (FIZZ)":["FIZZ","National"],
    "National Fuel Gas Company (NFG)":["NFG","National"],
    "National Health Investors Inc. (NHI)":["NHI","National"],
    "National Instruments Corporation (NATI)":["NATI","National"],
    "National Retail Properties (NNN)":["NNN","National"],
    "National Vision Holdings Inc. (EYE)":["EYE","National"],
    "Navient Corporation (NAVI)":["NAVI","Navient"],
    "Navistar International Corporation (NAV)":["NAV","Navistar"],
    "nCino Inc. (NCNO)":["NCNO","nCino"],
    "NCR Corporation (NCR)":["NCR","NCR"],
    "Nektar Therapeutics (NKTR)":["NKTR","Nektar"],
    "Nelnet Inc. (NNI)":["NNI","Nelnet"],
    "Neogen Corporation (NEOG)":["NEOG","Neogen"],
    "NeoGenomics Inc. (NEO)":["NEO","NeoGenomics"],
    "NetApp Inc. (NTAP)":["NTAP","NetApp"],
    "Netflix Inc. (NFLX)":["NFLX","Netflix"],
    "NetScout Systems Inc. (NTCT)":["NTCT","NetScout"],
    "Neurocrine Biosciences Inc. (NBIX)":["NBIX","Neurocrine"],
    "Nevro Corp. (NVRO)":["NVRO","Nevro"],
    "New Fortress Energy Inc. (NFE)":["NFE","New"],
    "New Relic Inc. (NEWR)":["NEWR","New"],
    "New Residential Investment Corp. (NRZ)":["NRZ","New"],
    "New York Community Bancorp Inc. (NYCB)":["NYCB","New"],
    "New York Times Company (NYT)":["NYT","New"],
    "Newell Brands Inc. (NWL)":["NWL","Newell"],
    "NewJersey Resources Corporation (NJR)":["NJR","NewJersey"],
    "NewMarket Corp (NEU)":["NEU","NewMarket"],
    "Newmont Corporation (NEM)":["NEM","Newmont"],
    "News Corporation (NWS)":["NWS","News"],
    "News Corporation (NWSA)":["NWSA","News"],
    "Nexstar Media Group Inc. (NXST)":["NXST","Nexstar"],
    "NextEra Energy Inc. (NEE)":["NEE","NextEra"],
    "NextEra Energy Partners LP (NEP)":["NEP","NextEra"],
    "NGM Biopharmaceuticals Inc. (NGM)":["NGM","NGM"],
    "NIC Inc (EGOV)":["EGOV","NIC"],
    "Nike Inc. (NKE)":["NKE","Nike"],
    "Nikola Corporation (NKLA)":["NKLA","Nikola"],
    "NiSource Inc (NI)":["NI","NiSource"],
    "Nordson Corporation (NDSN)":["NDSN","Nordson"],
    "Nordstrom Inc. (JWN)":["JWN","Nordstrom"],
    "Norfolk Southern Corporation (NSC)":["NSC","Norfolk"],
    "Northern Trust Corporation (NTRS)":["NTRS","Northern"],
    "Northrop Grumman Corporation (NOC)":["NOC","Northrop"],
    "NorthWestern Corporation (NWE)":["NWE","NorthWestern"],
    "NortonLifeLock Inc. (NLOK)":["NLOK","NortonLifeLock"],
    "Norwegian Cruise Line Holdings Ltd. (NCLH)":["NCLH","Norwegian"],
    "NOV Inc. (NOV)":["NOV","NOV"],
    "Novanta Inc. (NOVT)":["NOVT","Novanta"],
    "Novavax Inc. (NVAX)":["NVAX","Novavax"],
    "NRG Energy Inc. (NRG)":["NRG","NRG"],
    "Nu Skin Enterprises Inc. (NUS)":["NUS","Nu"],
    "Nuance Communications Inc. (NUAN)":["NUAN","Nuance"],
    "Nucor Corporation (NUE)":["NUE","Nucor"],
    "Nustar Energy L.P. (NS)":["NS","Nustar"],
    "Nutanix Inc. (NTNX)":["NTNX","Nutanix"],
    "NuVasive Inc. (NUVA)":["NUVA","NuVasive"],
    "Nuvation Bio Inc. (NUVB)":["NUVB","Nuvation"],
    "Nuveen AMT-Free Municipal Credit Income Fund (NVG)":["NVG","Nuveen"],
    "Nuveen AMT-Free Quality Municipal Income Fund (NEA)":["NEA","Nuveen"],
    "Nuveen California Quality Municipal Income Fund (NAC)":["NAC","Nuveen"],
    "Nuveen Municipal Credit Income Fund (NZF)":["NZF","Nuveen"],
    "Nuveen Municipal Value Fund Inc. (NUV)":["NUV","Nuveen"],
    "Nuveen Quality Municipal Income Fund (NAD)":["NAD","Nuveen"],
    "NVIDIA Corporation (NVDA)":["NVDA","NVIDIA"],
    "NVR Inc. (NVR)":["NVR","NVR"],
    "O-I Glass Inc. (OI)":["OI","O-I"],
    "O'Reilly Automotive Inc. (ORLY)":["ORLY","O'Reilly"],
    "Oak Street Health Inc. (OSH)":["OSH","Oak"],
    "Occidental Petroleum Corporation (OXY)":["OXY","Occidental"],
    "OGE Energy Corp (OGE)":["OGE","OGE"],
    "Okta Inc. (OKTA)":["OKTA","Okta"],
    "Old Dominion Freight Line Inc. (ODFL)":["ODFL","Old"],
    "Old National Bancorp (ONB)":["ONB","Old"],
    "Old Republic International Corporation (ORI)":["ORI","Old"],
    "Olin Corporation (OLN)":["OLN","Olin"],
    "Ollie's Bargain Outlet Holdings Inc. (OLLI)":["OLLI","Ollie's"],
    "Omega Healthcare Investors Inc. (OHI)":["OHI","Omega"],
    "Omnicell Inc. (OMCL)":["OMCL","Omnicell"],
    "Omnicom Group Inc. (OMC)":["OMC","Omnicom"],
    "ON Semiconductor Corporation (ON)":["ON","ON"],
    "ONEOK Inc. (OKE)":["OKE","ONEOK"],
    "Onto Innovation Inc. (ONTO)":["ONTO","Onto"],
    "Open Lending Corporation (LPRO)":["LPRO","Open"],
    "Open Text Corporation (OTEX)":["OTEX","Open"],
    "Opendoor Technologies Inc (OPEN)":["OPEN","Opendoor"],
    "OPKO Health Inc. (OPK)":["OPK","OPKO"],
    "Option Care Health Inc. (OPCH)":["OPCH","Option"],
    "Oracle Corporation (ORCL)":["ORCL","Oracle"],
    "Organogenesis Holdings Inc. (ORGO)":["ORGO","Organogenesis"],
    "Ormat Technologies Inc. (ORA)":["ORA","Ormat"],
    "Ortho Clinical Diagnostics plc (OCDX)":["OCDX","Ortho"],
    "Oshkosh Corporation (OSK)":["OSK","Oshkosh"],
    "Outset Medical Inc. (OM)":["OM","Outset"],
    "Overstock.com Inc. (OSTK)":["OSTK","Overstock.com"],
    "Ovintiv Inc. (OVV)":["OVV","Ovintiv"],
    "Owens & Minor Inc. (OMI)":["OMI","Owens"],
    "Owens Corning Inc New (OC)":["OC","Owens"],
    "PACCAR Inc. (PCAR)":["PCAR","PACCAR"],
    "Pacific Biosciences of California Inc. (PACB)":["PACB","Pacific"],
    "Pacific Gas & Electric Co. (PCG)":["PCG","Pacific"],
    "Pacific Premier Bancorp Inc (PPBI)":["PPBI","Pacific"],
    "Pacira BioSciences Inc. (PCRX)":["PCRX","Pacira"],
    "Packaging Corporation of America (PKG)":["PKG","Packaging"],
    "Pactiv Evergreen Inc. (PTVE)":["PTVE","Pactiv"],
    "PacWest Bancorp (PACW)":["PACW","PacWest"],
    "Palo Alto Networks Inc. (PANW)":["PANW","Palo"],
    "Pan American Silver Corp. (PAAS)":["PAAS","Pan"],
    "Papa John's International Inc. (PZZA)":["PZZA","Papa"],
    "Paramount Group Inc. (PGRE)":["PGRE","Paramount"],
    "Park Hotels & Resorts Inc. (PK)":["PK","Park"],
    "Parker-Hannifin Corporation (PH)":["PH","Parker-Hannifin"],
    "Patrick Industries Inc. (PATK)":["PATK","Patrick"],
    "Patterson Companies Inc. (PDCO)":["PDCO","Patterson"],
    "Paychex Inc. (PAYX)":["PAYX","Paychex"],
    "Paylocity Holding Corporation (PCTY)":["PCTY","Paylocity"],
    "PayPal Holdings Inc. (PYPL)":["PYPL","PayPal"],
    "PDC Energy Inc. (PDCE)":["PDCE","PDC"],
    "Pebblebrook Hotel Trust of Beneficial Interest (PEB)":["PEB","Pebblebrook"],
    "Pegasystems Inc. (PEGA)":["PEGA","Pegasystems"],
    "Peloton Interactive Inc. (PTON)":["PTON","Peloton"],
    "Pembina Pipeline Corp. (PBA)":["PBA","Pembina"],
    "Penn National Gaming Inc. (PENN)":["PENN","Penn"],
    "PennyMac Financial Services Inc. (PFSI)":["PFSI","PennyMac"],
    "Penske Automotive Group Inc. (PAG)":["PAG","Penske"],
    "People's United Financial Inc. (PBCT)":["PBCT","People's"],
    "PepsiCo Inc. (PEP)":["PEP","PepsiCo"],
    "Perficient Inc. (PRFT)":["PRFT","Perficient"],
    "Performance Food Group Company (PFGC)":["PFGC","Performance"],
    "PerkinElmer Inc. (PKI)":["PKI","PerkinElmer"],
    "Perrigo Company plc (PRGO)":["PRGO","Perrigo"],
    "Petco Health and Wellness Company Inc. (WOOF)":["WOOF","Petco"],
    "Pfizer Inc. (PFE)":["PFE","Pfizer"],
    "Philip Morris International Inc (PM)":["PM","Philip"],
    "Phillips 66 (PSX)":["PSX","Phillips"],
    "Phillips 66 Partners LP (PSXP)":["PSXP","Phillips"],
    "Phreesia Inc. (PHR)":["PHR","Phreesia"],
    "Physicians Realty Trust of Beneficial Interest (DOC)":["DOC","Physicians"],
    "Piedmont Office Realty Trust Inc. (PDM)":["PDM","Piedmont"],
    "Pilgrim's Pride Corporation (PPC)":["PPC","Pilgrim's"],
    "Pimco Corporate & Income Opportunity Fund (PTY)":["PTY","Pimco"],
    "Pinnacle Financial Partners Inc. (PNFP)":["PNFP","Pinnacle"],
    "Pinnacle West Capital Corporation (PNW)":["PNW","Pinnacle"],
    "Pioneer Natural Resources Company (PXD)":["PXD","Pioneer"],
    "Piper Sandler Companies (PIPR)":["PIPR","Piper"],
    "PJT Partners Inc. (PJT)":["PJT","PJT"],
    "Plains All American Pipeline L.P. (PAA)":["PAA","Plains"],
    "Planet Fitness Inc. (PLNT)":["PLNT","Planet"],
    "Plexus Corp. (PLXS)":["PLXS","Plexus"],
    "Plug Power Inc. (PLUG)":["PLUG","Plug"],
    "Pluralsight Inc. (PS)":["PS","Pluralsight"],
    "PNC Financial Services Group Inc. (PNC)":["PNC","PNC"],
    "PNM Resources Inc. (PNM)":["PNM","PNM"],
    "Polaris Inc. (PII)":["PII","Polaris"],
    "Pool Corporation (POOL)":["POOL","Pool"],
    "Popular Inc. (BPOP)":["BPOP","Popular"],
    "Portland General Electric Co (POR)":["POR","Portland"],
    "Poshmark Inc. (POSH)":["POSH","Poshmark"],
    "Post Holdings Inc. (POST)":["POST","Post"],
    "PotlatchDeltic Corporation (PCH)":["PCH","PotlatchDeltic"],
    "Power Integrations Inc. (POWI)":["POWI","Power"],
    "PPD Inc. (PPD)":["PPD","PPD"],
    "PPG Industries Inc. (PPG)":["PPG","PPG"],
    "PPL Corporation (PPL)":["PPL","PPL"],
    "PQ Group Holdings Inc. (PQG)":["PQG","PQ"],
    "PRA Health Sciences Inc. (PRAH)":["PRAH","PRA"],
    "Premier Inc. (PINC)":["PINC","Premier"],
    "Prestige Consumer Healthcare Inc. (PBH)":["PBH","Prestige"],
    "Pretium Resources Inc. (PVG)":["PVG","Pretium"],
    "PriceSmart Inc. (PSMT)":["PSMT","PriceSmart"],
    "Primerica Inc. (PRI)":["PRI","Primerica"],
    "Primo Water Corporation (PRMW)":["PRMW","Primo"],
    "Principal Financial Group Inc (PFG)":["PFG","Principal"],
    "Procter & Gamble Company (PG)":["PG","Procter"],
    "PROG Holdings Inc. (PRG)":["PRG","PROG"],
    "Progress Software Corporation (PRGS)":["PRGS","Progress"],
    "Progressive Corporation (PGR)":["PGR","Progressive"],
    "Progyny Inc. (PGNY)":["PGNY","Progyny"],
    "Prologis Inc. (PLD)":["PLD","Prologis"],
    "Proofpoint Inc. (PFPT)":["PFPT","Proofpoint"],
    "Prospect Capital Corporation (PSEC)":["PSEC","Prospect"],
    "Prosperity Bancshares Inc. (PB)":["PB","Prosperity"],
    "Proto Labs Inc. (PRLB)":["PRLB","Proto"],
    "Prudential Financial Inc. (PRU)":["PRU","Prudential"],
    "PS Business Parks Inc. (PSB)":["PSB","PS"],
    "PTC Inc. (PTC)":["PTC","PTC"],
    "PTC Therapeutics Inc. (PTCT)":["PTCT","PTC"],
    "Public Service Enterprise Group Incorporated (PEG)":["PEG","Public"],
    "Public Storage (PSA)":["PSA","Public"],
    "PubMatic Inc. (PUBM)":["PUBM","PubMatic"],
    "PulteGroup Inc. (PHM)":["PHM","PulteGroup"],
    "PureCycle Technologies Inc. (PCT)":["PCT","PureCycle"],
    "Purple Innovation Inc. (PRPL)":["PRPL","Purple"],
    "PVH Corp. (PVH)":["PVH","PVH"],
    "Qorvo Inc. (QRVO)":["QRVO","Qorvo"],
    "QTS Realty Trust Inc. (QTS)":["QTS","QTS"],
    "Quaker Chemical Corporation (KWR)":["KWR","Quaker"],
    "QUALCOMM Incorporated (QCOM)":["QCOM","QUALCOMM"],
    "Qualtrics International Inc. (XM)":["XM","Qualtrics"],
    "Qualys Inc. (QLYS)":["QLYS","Qualys"],
    "Quanta Services Inc. (PWR)":["PWR","Quanta"],
    "Quanterix Corporation (QTRX)":["QTRX","Quanterix"],
    "QuantumScape Corporation (QS)":["QS","QuantumScape"],
    "Quest Diagnostics Incorporated (DGX)":["DGX","Quest"],
    "Quidel Corporation (QDEL)":["QDEL","Quidel"],
    "Qurate Retail Inc. Series A (QRTEA)":["QRTEA","Qurate"],
    "Qurate Retail Inc. Series B (QRTEB)":["QRTEB","Qurate"],
    "R1 RCM Inc. (RCM)":["RCM","R1"],
    "Rackspace Technology Inc. (RXT)":["RXT","Rackspace"],
    "Radian Group Inc. (RDN)":["RDN","Radian"],
    "Ralph Lauren Corporation (RL)":["RL","Ralph"],
    "Rambus Inc. (RMBS)":["RMBS","Rambus"],
    "Range Resources Corporation (RRC)":["RRC","Range"],
    "Rapid7 Inc. (RPD)":["RPD","Rapid7"],
    "Raymond James Financial Inc. (RJF)":["RJF","Raymond"],
    "Rayonier Inc. REIT (RYN)":["RYN","Rayonier"],
    "Raytheon Technologies Corporation (RTX)":["RTX","Raytheon"],
    "RBC Bearings Incorporated (ROLL)":["ROLL","RBC"],
    "RealPage Inc. (RP)":["RP","RealPage"],
    "Realty Income Corporation (O)":["O","Realty"],
    "Reata Pharmaceuticals Inc. (RETA)":["RETA","Reata"],
    "Red Rock Resorts Inc. (RRR)":["RRR","Red"],
    "Redfin Corporation (RDFN)":["RDFN","Redfin"],
    "Regal Beloit Corporation (RBC)":["RBC","Regal"],
    "Regency Centers Corporation (REG)":["REG","Regency"],
    "Regeneron Pharmaceuticals Inc. (REGN)":["REGN","Regeneron"],
    "Regions Financial Corporation (RF)":["RF","Regions"],
    "Reinsurance Group of America Incorporated (RGA)":["RGA","Reinsurance"],
    "Relay Therapeutics Inc. (RLAY)":["RLAY","Relay"],
    "Reliance Steel & Aluminum Co. (RS)":["RS","Reliance"],
    "Renasant Corporation (RNST)":["RNST","Renasant"],
    "Renewable Energy Group Inc. (REGI)":["REGI","Renewable"],
    "Rent-A-Center Inc. (RCII)":["RCII","Rent-A-Center"],
    "Repligen Corporation (RGEN)":["RGEN","Repligen"],
    "Republic Services Inc. (RSG)":["RSG","Republic"],
    "ResMed Inc. (RMD)":["RMD","ResMed"],
    "Restaurant Brands International Inc. (QSR)":["QSR","Restaurant"],
    "Retail Properties of America Inc. (RPAI)":["RPAI","Retail"],
    "Revolution Medicines Inc. (RVMD)":["RVMD","Revolution"],
    "Rexford Industrial Realty Inc. (REXR)":["REXR","Rexford"],
    "Rexnord Corporation (RXN)":["RXN","Rexnord"],
    "Reynolds Consumer Products Inc. (REYN)":["REYN","Reynolds"],
    "RH (RH)":["RH","RH"],
    "Riot Blockchain Inc. (RIOT)":["RIOT","Riot"],
    "Ritchie Bros. Auctioneers Incorporated (RBA)":["RBA","Ritchie"],
    "RLI Corp. (RLI)":["RLI","RLI"],
    "Robert Half International Inc. (RHI)":["RHI","Robert"],
    "Rocket Companies Inc. (RKT)":["RKT","Rocket"],
    "Rocket Pharmaceuticals Inc. (RCKT)":["RCKT","Rocket"],
    "Rockwell Automation Inc. (ROK)":["ROK","Rockwell"],
    "Rogers Communication Inc. (RCI)":["RCI","Rogers"],
    "Rogers Corporation (ROG)":["ROG","Rogers"],
    "Roku Inc. (ROKU)":["ROKU","Roku"],
    "Rollins Inc. (ROL)":["ROL","Rollins"],
    "Root Inc. (ROOT)":["ROOT","Root"],
    "Roper Technologies Inc. (ROP)":["ROP","Roper"],
    "Ross Stores Inc. (ROST)":["ROST","Ross"],
    "Royal Bank Of Canada (RY)":["RY","Royal"],
    "Royal Gold Inc. (RGLD)":["RGLD","Royal"],
    "Royalty Pharma plc (RPRX)":["RPRX","Royalty"],
    "RPM International Inc. (RPM)":["RPM","RPM"],
    "Rubius Therapeutics Inc. (RUBY)":["RUBY","Rubius"],
    "Rush Enterprises Inc. (RUSHB)":["RUSHB","Rush"],
    "Rush Enterprises Inc. Cl A (RUSHA)":["RUSHA","Rush"],
    "Ryder System Inc. (R)":["R","Ryder"],
    "Ryman Hospitality Properties Inc. (RHP)":["RHP","Ryman"],
    "S&P Global Inc. (SPGI)":["SPGI","S&P"],
    "Sabra Health Care REIT Inc. (SBRA)":["SBRA","Sabra"],
    "Sabre Corporation (SABR)":["SABR","Sabre"],
    "Safehold Inc. (SAFE)":["SAFE","Safehold"],
    "Sage Therapeutics Inc. (SAGE)":["SAGE","Sage"],
    "Saia Inc. (SAIA)":["SAIA","Saia"],
    "SailPoint Technologies Holdings Inc. (SAIL)":["SAIL","SailPoint"],
    "Salesforce.com Inc (CRM)":["CRM","Salesforce.com"],
    "Sally Beauty Holdings Inc. (SBH)":["SBH","Sally"],
    "Sana Biotechnology Inc. (SANA)":["SANA","Sana"],
    "Sanderson Farms Inc. (SAFM)":["SAFM","Sanderson"],
    "Sandy Spring Bancorp Inc. (SASR)":["SASR","Sandy"],
    "Sanmina Corporation (SANM)":["SANM","Sanmina"],
    "Sarepta Therapeutics Inc. (SRPT)":["SRPT","Sarepta"],
    "SBA Communications Corporation (SBAC)":["SBAC","SBA"],
    "Schneider National Inc. (SNDR)":["SNDR","Schneider"],
    "Schrodinger Inc. (SDGR)":["SDGR","Schrodinger"],
    "Scientific Games Corp (SGMS)":["SGMS","Scientific"],
    "Scotts Miracle-Gro Company (SMG)":["SMG","Scotts"],
    "Sea Limited American (SE)":["SE","Sea"],
    "Seacoast Banking Corporation of Florida (SBCF)":["SBCF","Seacoast"],
    "Seagen Inc. (SGEN)":["SGEN","Seagen"],
    "Sealed Air Corporation (SEE)":["SEE","Sealed"],
    "SeaWorld Entertainment Inc. (SEAS)":["SEAS","SeaWorld"],
    "Seer Inc. (SEER)":["SEER","Seer"],
    "SEI Investments Company (SEIC)":["SEIC","SEI"],
    "Select Medical Holdings Corporation (SEM)":["SEM","Select"],
    "Selective Insurance Group Inc. (SIGI)":["SIGI","Selective"],
    "Sempra Energy (SRE)":["SRE","Sempra"],
    "Semtech Corporation (SMTC)":["SMTC","Semtech"],
    "Sensient Technologies Corporation (SXT)":["SXT","Sensient"],
    "Service Corporation International (SCI)":["SCI","Service"],
    "Service Properties Trust (SVC)":["SVC","Service"],
    "ServiceNow Inc. (NOW)":["NOW","ServiceNow"],
    "ServisFirst Bancshares Inc. (SFBS)":["SFBS","ServisFirst"],
    "Shake Shack Inc. (SHAK)":["SHAK","Shake"],
    "Shaw Communications Inc. (SJR)":["SJR","Shaw"],
    "Shell Midstream Partners L.P. (SHLX)":["SHLX","Shell"],
    "Shenandoah Telecommunications Co (SHEN)":["SHEN","Shenandoah"],
    "Sherwin-Williams Company (SHW)":["SHW","Sherwin-Williams"],
    "Shift4 Payments Inc. (FOUR)":["FOUR","Shift4"],
    "Shoals Technologies Group Inc. (SHLS)":["SHLS","Shoals"],
    "ShockWave Medical Inc. (SWAV)":["SWAV","ShockWave"],
    "Shopify Inc. Subordinate Voting Shares (SHOP)":["SHOP","Shopify"],
    "Shutterstock Inc. (SSTK)":["SSTK","Shutterstock"],
    "Signature Bank (SBNY)":["SBNY","Signature"],
    "Silgan Holdings Inc. (SLGN)":["SLGN","Silgan"],
    "Silicon Laboratories Inc. (SLAB)":["SLAB","Silicon"],
    "Silvergate Capital Corporation (SI)":["SI","Silvergate"],
    "Simmons First National Corporation (SFNC)":["SFNC","Simmons"],
    "Simon Property Group Inc. (SPG)":["SPG","Simon"],
    "Simpson Manufacturing Company Inc. (SSD)":["SSD","Simpson"],
    "Sinclair Broadcast Group Inc. (SBGI)":["SBGI","Sinclair"],
    "Sirius XM Holdings Inc. (SIRI)":["SIRI","Sirius"],
    "SITE Centers Corp. (SITC)":["SITC","SITE"],
    "SiteOne Landscape Supply Inc. (SITE)":["SITE","SiteOne"],
    "Six Flags Entertainment Corporation New (SIX)":["SIX","Six"],
    "Skechers U.S.A. Inc. (SKX)":["SKX","Skechers"],
    "Skyline Champion Corporation (SKY)":["SKY","Skyline"],
    "SkyWest Inc. (SKYW)":["SKYW","SkyWest"],
    "Skyworks Solutions Inc. (SWKS)":["SWKS","Skyworks"],
    "SL Green Realty Corp (SLG)":["SLG","SL"],
    "Sleep Number Corporation (SNBR)":["SNBR","Sleep"],
    "SLM Corporation (SLM)":["SLM","SLM"],
    "SM Energy Company (SM)":["SM","SM"],
    "Smartsheet Inc. (SMAR)":["SMAR","Smartsheet"],
    "SmileDirectClub Inc. (SDC)":["SDC","SmileDirectClub"],
    "Snap Inc. (SNAP)":["SNAP","Snap"],
    "Snap-On Incorporated (SNA)":["SNA","Snap-On"],
    "Snowflake Inc. (SNOW)":["SNOW","Snowflake"],
    "Sogou Inc. (SOGO)":["SOGO","Sogou"],
    "SolarWinds Corporation (SWI)":["SWI","SolarWinds"],
    "Sonic Automotive Inc. (SAH)":["SAH","Sonic"],
    "Sonoco Products Company (SON)":["SON","Sonoco"],
    "Sonos Inc. (SONO)":["SONO","Sonos"],
    "Sorrento Therapeutics Inc. (SRNE)":["SRNE","Sorrento"],
    "Sotera Health Company (SHC)":["SHC","Sotera"],
    "South Jersey Industries Inc. (SJI)":["SJI","South"],
    "South State Corporation (SSB)":["SSB","South"],
    "Southern Company (SO)":["SO","Southern"],
    "Southern Copper Corporation (SCCO)":["SCCO","Southern"],
    "Southwest Airlines Company (LUV)":["LUV","Southwest"],
    "Southwest Gas Holdings Inc. (SWX)":["SWX","Southwest"],
    "Southwestern Energy Company (SWN)":["SWN","Southwestern"],
    "Spectrum Brands Holdings Inc. (SPB)":["SPB","Spectrum"],
    "Spire Inc. (SR)":["SR","Spire"],
    "Spirit Aerosystems Holdings Inc. (SPR)":["SPR","Spirit"],
    "Spirit Airlines Inc. (SAVE)":["SAVE","Spirit"],
    "Spirit Realty Capital Inc. (SRC)":["SRC","Spirit"],
    "Splunk Inc. (SPLK)":["SPLK","Splunk"],
    "SpringWorks Therapeutics Inc. (SWTX)":["SWTX","SpringWorks"],
    "Sprout Social Inc (SPT)":["SPT","Sprout"],
    "Sprouts Farmers Market Inc. (SFM)":["SFM","Sprouts"],
    "SPS Commerce Inc. (SPSC)":["SPSC","SPS"],
    "SPX Corporation (SPXC)":["SPXC","SPX"],
    "SPX FLOW Inc. (FLOW)":["FLOW","SPX"],
    "Square Inc. (SQ)":["SQ","Square"],
    "SS&C Technologies Holdings Inc. (SSNC)":["SSNC","SS&C"],
    "SSR Mining Inc. (SSRM)":["SSRM","SSR"],
    "St. Joe Company (JOE)":["JOE","St."],
    "STAAR Surgical Company (STAA)":["STAA","STAAR"],
    "Stag Industrial Inc. (STAG)":["STAG","Stag"],
    "Stamps.com Inc. (STMP)":["STMP","Stamps.com"],
    "Stanley Black & Decker Inc. (SWK)":["SWK","Stanley"],
    "Stantec Inc (STN)":["STN","Stantec"],
    "Starbucks Corporation (SBUX)":["SBUX","Starbucks"],
    "STARWOOD PROPERTY TRUST INC. Starwood Property Trust Inc. (STWD)":["STWD","STARWOOD"],
    "State Street Corporation (STT)":["STT","State"],
    "Steel Dynamics Inc. (STLD)":["STLD","Steel"],
    "Stepan Company (SCL)":["SCL","Stepan"],
    "Stericycle Inc. (SRCL)":["SRCL","Stericycle"],
    "STERIS plc (STE)":["STE","STERIS"],
    "Sterling Bancorp (STL)":["STL","Sterling"],
    "Steven Madden Ltd. (SHOO)":["SHOO","Steven"],
    "Stifel Financial Corporation (SF)":["SF","Stifel"],
    "Stitch Fix Inc. (SFIX)":["SFIX","Stitch"],
    "STORE Capital Corporation (STOR)":["STOR","STORE"],
    "Strategic Education Inc. (STRA)":["STRA","Strategic"],
    "Stryker Corporation (SYK)":["SYK","Stryker"],
    "Summit Materials Inc. (SUM)":["SUM","Summit"],
    "Sun Communities Inc. (SUI)":["SUI","Sun"],
    "Sun Country Airlines Holdings Inc. (SNCY)":["SNCY","Sun"],
    "Sun Life Financial Inc. (SLF)":["SLF","Sun"],
    "Suncor Energy Inc. (SU)":["SU","Suncor"],
    "Sunnova Energy International Inc. (NOVA)":["NOVA","Sunnova"],
    "Sunoco LP (SUN)":["SUN","Sunoco"],
    "SunPower Corporation (SPWR)":["SPWR","SunPower"],
    "Sunrun Inc. (RUN)":["RUN","Sunrun"],
    "Sunstone Hotel Investors Inc. Sunstone Hotel Investors Inc. (SHO)":["SHO","Sunstone"],
    "Surgery Partners Inc. (SGRY)":["SGRY","Surgery"],
    "SVB Financial Group (SIVB)":["SIVB","SVB"],
    "SVMK Inc. (SVMK)":["SVMK","SVMK"],
    "Synaptics Incorporated $0.001 Par Value (SYNA)":["SYNA","Synaptics"],
    "Synchrony Financial (SYF)":["SYF","Synchrony"],
    "Syneos Health Inc. (SYNH)":["SYNH","Syneos"],
    "Synnex Corporation (SNX)":["SNX","Synnex"],
    "Synopsys Inc. (SNPS)":["SNPS","Synopsys"],
    "Synovus Financial Corp. (SNV)":["SNV","Synovus"],
    "Sysco Corporation (SYY)":["SYY","Sysco"],
    "T-Mobile US Inc. (TMUS)":["TMUS","T-Mobile"],
    "T. Rowe Price Group Inc. (TROW)":["TROW","T."],
    "Take-Two Interactive Software Inc. (TTWO)":["TTWO","Take-Two"],
    "Tandem Diabetes Care Inc. (TNDM)":["TNDM","Tandem"],
    "Tapestry Inc. (TPR)":["TPR","Tapestry"],
    "Targa Resources Inc. (TRGP)":["TRGP","Targa"],
    "Target Corporation (TGT)":["TGT","Target"],
    "Taylor Morrison Home Corporation (TMHC)":["TMHC","Taylor"],
    "TC Energy Corporation (TRP)":["TRP","TC"],
    "TCF Financial Corporation (TCF)":["TCF","TCF"],
    "TechTarget Inc. (TTGT)":["TTGT","TechTarget"],
    "Teck Resources Ltd (TECK)":["TECK","Teck"],
    "TEGNA Inc (TGNA)":["TGNA","TEGNA"],
    "Teladoc Health Inc. (TDOC)":["TDOC","Teladoc"],
    "Teledyne Technologies Incorporated (TDY)":["TDY","Teledyne"],
    "Teleflex Incorporated (TFX)":["TFX","Teleflex"],
    "Telephone and Data Systems Inc. (TDS)":["TDS","Telephone"],
    "Telos Corporation (TLS)":["TLS","Telos"],
    "Telus Corporation (TU)":["TU","Telus"],
    "Tempur Sealy International Inc. (TPX)":["TPX","Tempur"],
    "Tenable Holdings Inc. (TENB)":["TENB","Tenable"],
    "Tenet Healthcare Corporation (THC)":["THC","Tenet"],
    "Teradata Corporation (TDC)":["TDC","Teradata"],
    "Teradyne Inc. (TER)":["TER","Teradyne"],
    "Terex Corporation (TEX)":["TEX","Terex"],
    "Terreno Realty Corporation (TRNO)":["TRNO","Terreno"],
    "Tesla Inc. (TSLA)":["TSLA","Tesla"],
    "Tetra Tech Inc. (TTEK)":["TTEK","Tetra"],
    "Texas Capital Bancshares Inc. (TCBI)":["TCBI","Texas"],
    "Texas Instruments Incorporated (TXN)":["TXN","Texas"],
    "Texas Pacific Land Corporation (TPL)":["TPL","Texas"],
    "Texas Roadhouse Inc. (TXRH)":["TXRH","Texas"],
    "Textron Inc. (TXT)":["TXT","Textron"],
    "TFS Financial Corporation (TFSL)":["TFSL","TFS"],
    "TG Therapeutics Inc. (TGTX)":["TGTX","TG"],
    "The AES Corporation (AES)":["AES","The"],
    "The AZEK Company Inc. (AZEK)":["AZEK","The"],
    "The Bank of New York Mellon Corporation (BK)":["BK","The"],
    "The Blackstone Group Inc. (BX)":["BX","The"],
    "The Carlyle Group Inc. (CG)":["CG","The"],
    "The Cooper Companies Inc. (COO)":["COO","The"],
    "The Ensign Group Inc. (ENSG)":["ENSG","The"],
    "The Goodyear Tire & Rubber Company (GT)":["GT","The"],
    "The Hershey Company (HSY)":["HSY","The"],
    "The Kraft Heinz Company (KHC)":["KHC","The"],
    "The Michaels Companies Inc. (MIK)":["MIK","The"],
    "The ODP Corporation (ODP)":["ODP","The"],
    "The RealReal Inc. (REAL)":["REAL","The"],
    "The Simply Good Foods Company (SMPL)":["SMPL","The"],
    "The Trade Desk Inc. (TTD)":["TTD","The"],
    "The Travelers Companies Inc. (TRV)":["TRV","The"],
    "Thermo Fisher Scientific Inc (TMO)":["TMO","Thermo"],
    "Thomson Reuters Corp (TRI)":["TRI","Thomson"],
    "Thor Industries Inc. (THO)":["THO","Thor"],
    "Tilray Inc. Class 2 (TLRY)":["TLRY","Tilray"],
    "Timken Company (TKR)":["TKR","Timken"],
    "TJX Companies Inc. (TJX)":["TJX","TJX"],
    "Toll Brothers Inc. (TOL)":["TOL","Toll"],
    "Tootsie Roll Industries Inc. (TR)":["TR","Tootsie"],
    "TopBuild Corp. (BLD)":["BLD","TopBuild"],
    "Toro Company (TTC)":["TTC","Toro"],
    "Toronto Dominion Bank (TD)":["TD","Toronto"],
    "TowneBank (TOWN)":["TOWN","TowneBank"],
    "TPI Composites Inc. (TPIC)":["TPIC","TPI"],
    "Tractor Supply Company (TSCO)":["TSCO","Tractor"],
    "Tradeweb Markets Inc. (TW)":["TW","Tradeweb"],
    "TransAlta Corporation (TAC)":["TAC","TransAlta"],
    "Transdigm Group Incorporated Transdigm Group Inc. (TDG)":["TDG","Transdigm"],
    "TransUnion (TRU)":["TRU","TransUnion"],
    "Travel Leisure Co. Common Stock (TNL)":["TNL","Travel"],
    "Treehouse Foods Inc. (THS)":["THS","Treehouse"],
    "Trex Company Inc. (TREX)":["TREX","Trex"],
    "Tri Pointe Homes Inc. (TPH)":["TPH","Tri"],
    "Trimble Inc. (TRMB)":["TRMB","Trimble"],
    "Trinity Industries Inc. (TRN)":["TRN","Trinity"],
    "TripAdvisor Inc. (TRIP)":["TRIP","TripAdvisor"],
    "Triumph Bancorp Inc. (TBK)":["TBK","Triumph"],
    "Tronox Holdings plc (TROX)":["TROX","Tronox"],
    "Truist Financial Corporation (TFC)":["TFC","Truist"],
    "Trupanion Inc. (TRUP)":["TRUP","Trupanion"],
    "Trustmark Corporation (TRMK)":["TRMK","Trustmark"],
    "TTEC Holdings Inc. (TTEC)":["TTEC","TTEC"],
    "Turning Point Therapeutics Inc. (TPTX)":["TPTX","Turning"],
    "Turquoise Hill Resources Ltd. (TRQ)":["TRQ","Turquoise"],
    "Twilio Inc. (TWLO)":["TWLO","Twilio"],
    "Twist Bioscience Corporation (TWST)":["TWST","Twist"],
    "Two Harbors Investment Corp (TWO)":["TWO","Two"],
    "Tyler Technologies Inc. (TYL)":["TYL","Tyler"],
    "Tyson Foods Inc. (TSN)":["TSN","Tyson"],
    "U.S. Bancorp (USB)":["USB","U.S."],
    "Ubiquiti Inc. (UI)":["UI","Ubiquiti"],
    "UDR Inc. (UDR)":["UDR","UDR"],
    "UFP Industries Inc. (UFPI)":["UFPI","UFP"],
    "UGI Corporation (UGI)":["UGI","UGI"],
    "Ulta Beauty Inc. (ULTA)":["ULTA","Ulta"],
    "Ultra Clean Holdings Inc. (UCTT)":["UCTT","Ultra"],
    "Ultragenyx Pharmaceutical Inc. (RARE)":["RARE","Ultragenyx"],
    "UMB Financial Corporation (UMBF)":["UMBF","UMB"],
    "Umpqua Holdings Corporation (UMPQ)":["UMPQ","Umpqua"],
    "Under Armour Inc. (UA)":["UA","Under"],
    "Under Armour Inc. (UAA)":["UAA","Under"],
    "Unifirst Corporation (UNF)":["UNF","Unifirst"],
    "Union Pacific Corporation (UNP)":["UNP","Union"],
    "United Airlines Holdings Inc. (UAL)":["UAL","United"],
    "United Bankshares Inc. (UBSI)":["UBSI","United"],
    "United Community Banks Inc. (UCBI)":["UCBI","United"],
    "United Parcel Service Inc. (UPS)":["UPS","United"],
    "United Rentals Inc. (URI)":["URI","United"],
    "United States Cellular Corporation (USM)":["USM","United"],
    "United States Steel Corporation (X)":["X","United"],
    "United Therapeutics Corporation (UTHR)":["UTHR","United"],
    "UnitedHealth Group Incorporated (UNH)":["UNH","UnitedHealth"],
    "Uniti Group Inc. (UNIT)":["UNIT","Uniti"],
    "Unity Software Inc. (U)":["U","Unity"],
    "Univar Solutions Inc. (UNVR)":["UNVR","Univar"],
    "Universal Display Corporation (OLED)":["OLED","Universal"],
    "Universal Health Services Inc. (UHS)":["UHS","Universal"],
    "Unum Group (UNM)":["UNM","Unum"],
    "Upstart Holdings Inc. (UPST)":["UPST","Upstart"],
    "Upwork Inc. (UPWK)":["UPWK","Upwork"],
    "Urban Outfitters Inc. (URBN)":["URBN","Urban"],
    "US Foods Holding Corp. (USFD)":["USFD","US"],
    "USANA Health Sciences Inc. (USNA)":["USNA","USANA"],
    "Utz Brands Inc (UTZ)":["UTZ","Utz"],
    "UWM Holdings Corporation (UWMC)":["UWMC","UWM"],
    "V.F. Corporation (VFC)":["VFC","V.F."],
    "Vail Resorts Inc. (MTN)":["MTN","Vail"],
    "Valero Energy Corporation (VLO)":["VLO","Valero"],
    "Valley National Bancorp (VLY)":["VLY","Valley"],
    "Valmont Industries Inc. (VMI)":["VMI","Valmont"],
    "Valvoline Inc. (VVV)":["VVV","Valvoline"],
    "Varian Medical Systems Inc. (VAR)":["VAR","Varian"],
    "Varonis Systems Inc. (VRNS)":["VRNS","Varonis"],
    "Vector Group Ltd. (VGR)":["VGR","Vector"],
    "Velodyne Lidar Inc. (VLDR)":["VLDR","Velodyne"],
    "Ventas Inc. (VTR)":["VTR","Ventas"],
    "Veracyte Inc. (VCYT)":["VCYT","Veracyte"],
    "VEREIT Inc. (VER)":["VER","VEREIT"],
    "Vericel Corporation (VCEL)":["VCEL","Vericel"],
    "Verint Systems Inc. (VRNT)":["VRNT","Verint"],
    "VeriSign Inc. (VRSN)":["VRSN","VeriSign"],
    "Verisk Analytics Inc. (VRSK)":["VRSK","Verisk"],
    "Verra Mobility Corporation (VRRM)":["VRRM","Verra"],
    "Vertex Inc. (VERX)":["VERX","Vertex"],
    "Vertex Pharmaceuticals Incorporated (VRTX)":["VRTX","Vertex"],
    "Vertiv Holdings LLC (VRT)":["VRT","Vertiv"],
    "ViacomCBS Inc. (VIAC)":["VIAC","ViacomCBS"],
    "ViacomCBS Inc. (VIACA)":["VIACA","ViacomCBS"],
    "Viant Technology Inc. (DSP)":["DSP","Viant"],
    "ViaSat Inc. (VSAT)":["VSAT","ViaSat"],
    "Viatris Inc. (VTRS)":["VTRS","Viatris"],
    "Viavi Solutions Inc. (VIAV)":["VIAV","Viavi"],
    "Vicor Corporation (VICR)":["VICR","Vicor"],
    "Viper Energy Partners LP (VNOM)":["VNOM","Viper"],
    "Vir Biotechnology Inc. (VIR)":["VIR","Vir"],
    "Virtu Financial Inc. (VIRT)":["VIRT","Virtu"],
    "Visa Inc. (V)":["V","Visa"],
    "Vishay Intertechnology Inc. (VSH)":["VSH","Vishay"],
    "Visteon Corporation (VC)":["VC","Visteon"],
    "Vmware Inc. (VMW)":["VMW","Vmware"],
    "Vonage Holdings Corp. (VG)":["VG","Vonage"],
    "Vornado Realty Trust (VNO)":["VNO","Vornado"],
    "Voya Financial Inc. (VOYA)":["VOYA","Voya"],
    "Vroom Inc. (VRM)":["VRM","Vroom"],
    "Vulcan Materials Company (VMC)":["VMC","Vulcan"],
    "W. P. Carey Inc. REIT (WPC)":["WPC","W."],
    "W.R. Berkley Corporation (WRB)":["WRB","W.R."],
    "W.R. Grace & Co. (GRA)":["GRA","W.R."],
    "W.W. Grainger Inc. (GWW)":["GWW","W.W."],
    "Walgreens Boots Alliance Inc. (WBA)":["WBA","Walgreens"],
    "Walker & Dunlop Inc (WD)":["WD","Walker"],
    "Walmart Inc. (WMT)":["WMT","Walmart"],
    "Walt Disney Company (DIS)":["DIS","Disney"],
    "Warner Music Group Corp. (WMG)":["WMG","Warner"],
    "Washington Federal Inc. (WAFD)":["WAFD","Washington"],
    "Waste Connections Inc. (WCN)":["WCN","Waste"],
    "Waste Management Inc. (WM)":["WM","Waste"],
    "Waters Corporation (WAT)":["WAT","Waters"],
    "Watsco Inc. (WSO)":["WSO","Watsco"],
    "Watts Water Technologies Inc. (WTS)":["WTS","Watts"],
    "Wayfair Inc. (W)":["W","Wayfair"],
    "WD-40 Company (WDFC)":["WDFC","WD-40"],
    "Webster Financial Corporation (WBS)":["WBS","Webster"],
    "WEC Energy Group Inc. (WEC)":["WEC","WEC"],
    "Weingarten Realty Investors (WRI)":["WRI","Weingarten"],
    "Wells Fargo & Company (WFC)":["WFC","Wells"],
    "Welltower Inc. (WELL)":["WELL","Welltower"],
    "Wendy's Company (WEN)":["WEN","Wendy's"],
    "Werner Enterprises Inc. (WERN)":["WERN","Werner"],
    "WesBanco Inc. (WSBC)":["WSBC","WesBanco"],
    "WESCO International Inc. (WCC)":["WCC","WESCO"],
    "West Pharmaceutical Services Inc. (WST)":["WST","West"],
    "Western Alliance Bancorporation (WAL)":["WAL","Western"],
    "Western Digital Corporation (WDC)":["WDC","Western"],
    "Western Midstream Partners LP (WES)":["WES","Western"],
    "Western Union Company (WU)":["WU","Western"],
    "Westinghouse Air Brake Technologies Corporation (WAB)":["WAB","Westinghouse"],
    "Westlake Chemical Corporation (WLK)":["WLK","Westlake"],
    "WEX Inc. (WEX)":["WEX","WEX"],
    "Weyerhaeuser Company (WY)":["WY","Weyerhaeuser"],
    "Wheaton Precious Metals Corp (WPM)":["WPM","Wheaton"],
    "Whirlpool Corporation (WHR)":["WHR","Whirlpool"],
    "White Mountains Insurance Group Ltd. (WTM)":["WTM","White"],
    "Williams Companies Inc. (WMB)":["WMB","Williams"],
    "Williams-Sonoma Inc. (WSM)":["WSM","Williams-Sonoma"],
    "WillScot Mobile Mini Holdings Corp. (WSC)":["WSC","WillScot"],
    "Wingstop Inc. (WING)":["WING","Wingstop"],
    "Winnebago Industries Inc. (WGO)":["WGO","Winnebago"],
    "Wintrust Financial Corporation (WTFC)":["WTFC","Wintrust"],
    "Wolverine World Wide Inc. (WWW)":["WWW","Wolverine"],
    "Woodward Inc. (WWD)":["WWD","Woodward"],
    "Workday Inc. (WDAY)":["WDAY","Workday"],
    "Workiva Inc. (WK)":["WK","Workiva"],
    "World Fuel Services Corporation (INT)":["INT","World"],
    "World Wrestling Entertainment Inc. (WWE)":["WWE","World"],
    "Worthington Industries Inc. (WOR)":["WOR","Worthington"],
    "WSFS Financial Corporation (WSFS)":["WSFS","WSFS"],
    "WW International Inc. (WW)":["WW","WW"],
    "Wynn Resorts Limited (WYNN)":["WYNN","Wynn"],
    "Xcel Energy Inc. (XEL)":["XEL","Xcel"],
    "Xencor Inc. (XNCR)":["XNCR","Xencor"],
    "Xenia Hotels & Resorts Inc. (XHR)":["XHR","Xenia"],
    "Xerox Holdings Corporation (XRX)":["XRX","Xerox"],
    "Xilinx Inc. (XLNX)":["XLNX","Xilinx"],
    "Xperi Holding Corporation (XPER)":["XPER","Xperi"],
    "XPO Logistics Inc. (XPO)":["XPO","XPO"],
    "Xylem Inc. New (XYL)":["XYL","Xylem"],
    "Yamana Gold Inc. (AUY)":["AUY","Yamana"],
    "Yelp Inc. (YELP)":["YELP","Yelp"],
    "YETI Holdings Inc. (YETI)":["YETI","YETI"],
    "Yum China Holdings Inc. (YUMC)":["YUMC","Yum"],
    "Yum! Brands Inc. (YUM)":["YUM","Yum!"],
    "Zebra Technologies Corporation (ZBRA)":["ZBRA","Zebra"],
    "Zillow Group Inc. (ZG)":["ZG","Zillow"],
    "Zillow Group Inc. Capital Stock (Z)":["Z","Zillow"],
    "Zimmer Biomet Holdings Inc. (ZBH)":["ZBH","Zimmer"],
    "Zions Bancorporation N.A. (ZION)":["ZION","Zions"],
    "Zoetis Inc. (ZTS)":["ZTS","Zoetis"],
    "Zoom Video Communications Inc. (ZM)":["ZM","Zoom"],
    "ZoomInfo Technologies Inc. (ZI)":["ZI","ZoomInfo"],
    "Zscaler Inc. (ZS)":["ZS","Zscaler"],
    "Zynga Inc. (ZNGA)":["ZNGA","Zynga"],
}

filename = 'tickers.pickle'
outfile=open(filename,'wb')

pickle.dump(ticker_list,outfile)
outfile.close()